### ISSUE TITLE
SSH to paloalto_panos with pre-login interactive banner enabled

### ISSUE THREAD

**Issue by BeardedAnalyst** [ktbyers/netmiko#1001]
When a pre-login interactive banner is enabled on a Palo Alto device ssh connections with Netmiko fail. An example of the pre-login banner can be seen below:

`ba@deverv:~/scripts$ ssh user@ip
This is the consent banner that will force the administrator to answer yes or no before they are prompted for the password.
Do you accept and acknowledge the statement above ? (yes/no) :`

**Comment by edkee82** [comment]
Facing a similar problem. As per my setup, it seems I would need to change the connectHandler function for connecting few devices. This is because from my machine when I give ssh <device name>, first I am asked for a certain password (which is password for an intermediate jump server), and then I am asked for the password for the device. Can you please suggest if this is doable in Netmiko ?

**Comment by geracastro** [comment]
Hello all. Anything new on this one?

**Comment by ktbyers** [comment]
Can someone with a pan-os device test this proposed fix?

https://github.com/ktbyers/netmiko/pull/2227

We need to test both when the acknowledgement banner exists and also when it doesn't exist.

**Comment by ktbyers** [comment]
@geracastro @edkee82 @BeardedAnalyst Any possibility one of you could test this fix?

https://github.com/ktbyers/netmiko/pull/2227

**Comment by ktbyers** [comment]
Only took a bit under three years, but this should be fixed now :-)

Fix is here:

https://github.com/ktbyers/netmiko/pull/2227
