### ISSUE TITLE
not able to execute code

### ISSUE THREAD

**Issue by manishrawat221** [ktbyers/netmiko#1106]
Below is script and error getting :---

#!/usr/bin/env python

from netmiko import ConnectHandler
from getpass import getpass
import sys

f = open("IP_Add")
for line in f:
   print "Configuring in Device having IP " + (line)
   HOST = line

   iosv_l2 = {
       'device_type': 'cisco_ios',
       'ip': 'HOST',
       'username': raw_input("Enter username: "),
       'password': getpass(),
   }
   net_connect = ConnectHandler(**iosv_l2)
   output = net_connect.send_command('show ip int brief')
   print output

   config_commands = ['int loop 10', 'ip address 10.1.1.1 255.255.255.0', 'end'
, 'wr' ]
   output = net_connect.send_config_set(config_commands)
   print output

BELOW IS ERROR COMING

root@NetworkAutomation-1:~# python test2
Configuring in Device having IP 192.168.122.72

Enter username: cisco
Password:
Traceback (most recent call last):
  File "test2", line 18, in <module>
    net_connect = ConnectHandler(**iosv_l2)
  File "/usr/local/lib/python2.7/dist-packages/netmiko/ssh_dispatcher.py", line 218, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/netmiko/base_connection.py", line 270, in __init__
    self.establish_connection()
  File "/usr/local/lib/python2.7/dist-packages/netmiko/base_connection.py", line 787, in establish_connection
    raise NetMikoTimeoutException(msg)
netmiko.ssh_exception.NetMikoTimeoutException: Connection to device timed-out: cisco_ios HOST:22

**Comment by OzNetNerd** [comment]
A few things:

1. You should use Python 3 instead of 2.
2. Take a look at `with open` (context manager) as opposed to `open`.
3. If `HOST` = `line`, why not just use `line` directly?
4. I'd move `raw_input("Enter username: ")` and `getpass()` out of the dict.
5. The cause of your problem is the quotes around HOST -  `'ip': 'HOST'` - Try `'ip': HOST` or `'ip': line` instead. You can see this in the traceback message: `timed-out: cisco_ios HOST:22`

**Comment by carlniger** [comment]
inactive. closing.
