### ISSUE TITLE
Should setuptools or distutils be used

### ISSUE THREAD

**Issue by ktbyers** [ktbyers/netmiko#112]

**Comment by colinmcintosh** [comment]
In a weird coincidence I just sent you a pull request for this. I probably should have checked the issues first. I put my reasoning for why I think it should be setuptools in the pull request. 

https://github.com/ktbyers/netmiko/pull/113

**Comment by colinmcintosh** [comment]
Copy paste:

This change is to add support for the install_requires parameter passed to the setup()
function. Distutils does not support install_requires and therefore will
not automatically resolve dependencies for setup.py. In addition the lack
of support for install_requires creates problems for packages that specify
netmiko as a dependency. The dependency tree will not be created correctly
and will attempt to install netmiko before paramiko or scp if they are
specified in as a dependency as well.

A concern for this might be that setuptools is not a built-in Python
library while distutils is. I feel that this does not greatly affect
compatibility with existing deployment scenarios because setuptools is
included by default with Python3+ as of PEP0453 and Python2.7 as of
PEP0477. These PEPs specify that pip be included in Python as a default
and setuptools is a requirement of pip.

See here:
https://www.python.org/dev/peps/pep-0453/#automatic-installation-of-setuptools

**Comment by ktbyers** [comment]
This has been fixed.
