### ISSUE TITLE
send_command output fails to strip the prompt when target hostname changes

### ISSUE THREAD

**Issue by Ragsboss** [ktbyers/netmiko#1157]
**Repro steps**
1. Install 'netmiko==2.3.0'
2. Connect to a target device using ssh
3. Hostname of target device is set to `leaf1`
4. Execute a command using `send_command` method and observe the output is coming as expected
5. Change the hostname on target device to `spine1`
6. Execute the same command as in step 4

**Expected**: The output is as expected
**Actual**: The output contains an extra line.

Below program from python shell illustrates the above sequence
```
>>> from netmiko import ConnectHandler
>>> d = ConnectHandler(device_type='dell_os10', ip='172.20.55.6', username='blah', password='blah')
>>> d.base_prompt
u'leaf1'
>>> print d.send_command('show clock')
2019-03-29T23:55:19.89+00:00
>>> # change hostname on target device to 'spine1'
>>> print d.send_command('show clock')
2019-03-29T23:56:09.80+00:00
spine1# 
>>> d.set_base_prompt()
u'spine1'
>>> print d.send_command('show clock')
2019-03-29T23:56:19.02+00:00
>>> 
```

**Root cause and suggested fix**
`BaseConnection.send_command` is fetching the changed prompt correctly, but `BaseConnection.strip_prompt` relies on `BaseConnection.base_prompt` which still refers to old prompt and hence it's not stripped

The suggested fix is to send the `prompt` used in `send_command` method to `strip_prompt` method. The `strip_prompt` method can use passed in prompt value or fallback to `self.base_prompt`. Alternatively we can proactively update `self.base_prompt` as part of `send_command` but I'm not sure about any undesired consequences of this implicit state mutation.

**Workaround**
Anyways, the work-around is to call `set_base_prompt` before `send_command` call and pass `auto_find_prompt=False` to avoid re-fetching the prompt again..

**Comment by ktbyers** [comment]
Yes, this is known and expected. 

As you mentioned above the fix is to call the `set_base_prompt()` method after a hostname change.

I don't think the added complexity of your other proposed fix is worth it.

**Comment by Ragsboss** [comment]
@ktbyers thank you for looking into the issue.

When someone calls `send_command(cmd_string, auto_find_prompt=True, expect_string=None)` the expectation is this method makes an explicit effort to find the prompt before dispatching the command. The method indeed does that but does not use the freshly retrieved prompt when it comes to stripping the prompt. This, imho and with all respect, is clearly a bug.

In many cases, automation code is using `netmiko` and that code wouldn't know when the hostname changes on the target. In fact, this is how I found this issue - our code failed to parse the XML due to the extra line at the end..

I'm also not sure that proposed fix is complex. Adding an optional arg to `strip_prompt` is a localized change that is fully backward compatible. Anyways I respect your judgement here given you totally know this code much better than me :)

I'd appreciate if you can reconsider your stance from the automation use cases viewpoint. If you still feel risk outweighs the benefit, we'll live with it...

**Comment by ktbyers** [comment]
@Ragsboss Let me mull it some more...I am definitely concerned about things such as:

1)How do you know whether a prompt change has happened (do you have to take an overhead time of figuring this out automatically every time and what is the overall performance penalty of this)?

2)Will this meaningfully reduce reliability of output printing due to capturing transitory prompt change states (for example, going into config mode, sub-config mode et cetera)?

3)Will this meaningfully reduce reliability in other contexts--some Netmiko operations intentionally don't fine the prompt name (or the code breaks).

How would you not know that the hostname was changed? Are you saying the hostname was changed by something besides Netmiko?

**Comment by Ragsboss** [comment]
1) With `send_command(cmd_string, auto_find_prompt=True, expect_string=None)`, we are anyways finding the prompt on every call - if we do the change, at-least for this case, there is no difference in performance

2) Valid point. This maybe a hint for us to not change the `self.base_prompt` and instead just use the freshly determined prompt also for prompt stripping logic

3) I'm guessing such cases would not set `auto_find_prompt=True` with `expect_string=None` which is an explicit trigger for prompt finding

In our case, the hostname was indeed changed out-of-band by a human (typing at the console) and the main (monitoring) script using netmiko was affected..

**Comment by ktbyers** [comment]
1. Yes, but using `expect_string` is a very common pattern and the same problem exists there (and I would be reluctant to have inconsistent behavior). Also send_command_timing strips the prompt--once again would be reluctant to have inconsistent behavior.

Your case is a very edge case. In vast, vast majority of the situations it will be Netmiko that changed the prompt.

**Comment by edgar-costa** [comment]
What about the case in which sending a command will change the expected prompt? 

For example in a cisco router when you do: `interface <>` the prompt goes from `(config)#` to `(config-if)#`. And this is just an example there are many other cases. If for those commands you do not specify the `expect_string` it does not work. Unless there is a way to overcome this, I find the fact that for every command you need to know the expected prompt a bit annoying and makes the logic a bit more complex. Am I missing something in my specific case or the same answer you gave to OP applies here?

**Comment by ktbyers** [comment]
@edgar-costa For config changes, Netmiko just grabs the whole config session output so that is really not an issue. You will have the whole config change output and the issue only concerns the final trailing prompt at the end of the config session output.

For config changes, you should use send_config_set or send_config_from_file so you should not need to specify expect_string.

**Comment by ktbyers** [comment]
I don't think this issue is worth fixing so I am going to close. There are already workarounds that exist for situations where it is Netmiko that changes the hostname. 

If it is changed by another process/user besides Netmiko, then one this is a rare case and you likely have significant issues that are larger than the trailing prompt issue.
