### ISSUE TITLE
HUAWEI S5700-52X-LI-48CS-AC save the config

### ISSUE THREAD

**Issue by kristoferus75** [ktbyers/netmiko#1163]
Hi !

from netmiko.huawei import HuaweiSSH, HuaweiVrpv8SSH
#
'device_type': 'huawei_vrpv8',

save the configuration doesn't work !
 HUAWEI S5700-52X-LI-48CS-AC

net_connect.save_config('save')

no error but changes are not in the saved config:
display saved-configuration
but in the
display current-configuration are the changes visable !

netmiko 2.3.3 

Please help !

kind regards kristoferus75

**Comment by OzNetNerd** [comment]
It appears that it's [not implemented](https://github.com/ktbyers/netmiko/blob/develop/netmiko/huawei/huawei_ssh.py#L128-L130). Given that you're not seeing the exception being raised, I assume you've got your code in a `try`/`except` block.

In regards to saving your config, perhaps [commit](https://github.com/ktbyers/netmiko/blob/develop/netmiko/huawei/huawei_ssh.py#L92) is what you're looking for?

**Comment by carlniger** [comment]
A PR has been merged into develop to ensure that `NotImplementedError ` is raised if the save method doesn't exist : #1187 Otherwise as @OzNetNerd said you may be after commit; I'm a bit fuzzy on the Huawei syntax/commands but you may need to send that as the last command in a config set. Going to close this, feel  free to reopen if needed.
