### ISSUE TITLE
Unable to login to Ruckus device with custom ssh parameters

### ISSUE THREAD

**Issue by mamjuu** [ktbyers/netmiko#1251]
I would like to use netmiko to login to Ruckus boxes which are not using default ssh connection parameters. 
This is what I have in my .bashrc

`function ruckusssh_fn(){
      sudo ssh -p22 -o KexAlgorithms=+diffie-hellman-group1-sha1 -o HostKeyAlgorithms=+ssh-dss -c aes128-ctr,aes192-ctr,aes256-ctr,aes128-cbc,3des-cbc username@"$1";
}
alias ruckusssh=ruckusssh_fn;`

And then when I want to login, I type ruckusssh ip_address_of_device

Now I would like to use netmiko to login to such devices. But I am not able to find the relevant parameters I need to add to let it login.

**Comment by carlniger** [comment]
Do you get a paramiko exception when trying to log into the ruckus host? Looks like you're just passing port and kex/ciphers which paramiko should handle anyway. You can pass an OpenSSH config file to netmiko though via the ConnectHandler `ssh_config_file` argument so you should be able to set whatever you want in there (including user if you want).

I'm going to close this, but feel free to re-open if you have a Netmiko issue/bug. Otherwise, feel free to join the Pynet slack community [here](https://join.slack.com/t/pynet/shared_invite/enQtNTA2MDI3NjU0MTM0LTQ5MjExNGNlNWIzMmRhOTZmNmZkNDA2Nzk4Y2Q1Y2RkMWNhZGEzM2Y5MjI0NDYxODkzM2M0ODIwYzFkMzVmZGY) where you can find a dedicated netmiko channel for questions/comments/etc if you're still having any issues.
