### ISSUE TITLE
raw_input() in send_command() gives "unknown command" error

### ISSUE THREAD

**Issue by elina89virgo** [ktbyers/netmiko#1296]
Hello everyone!

I am fairly new to Python and Netmiko. I decided that alongside with learning Python, I should try to write simple scripts for Juniper JunOS.
Here is an extract of my script:

     nni_port = raw_input('Please enter exact port you want to check light levels on: ')
     check_nni_port = net_connect.send_command("show interfaces diagnostics optics" + 
     nni_port)
     print(check_nni_port)

Intention: get a user type in an interface name, like "ge-0/0/0" and throw that in as raw_input into a send_command.

When running the script, I get a prompt for interface name, but once type that up, I get "unknown command".
My guesses: 1) I messed up formatting; 2) there is some intricacy with send_command that I am not aware of; 3) there is some issue with those forward slashes.

Note: when user is prompted to type up the whole command and it is thrown into send_command as raw_input, command works just fine.

nni_port = raw_input('Please enter command "show interfaces diagnostics optics" plus exact port you want to check light levels on: ')
check_nni_port = net_connect.send_command(nni_port)

Kindly advise.

**Comment by ktbyers** [comment]
@elina89virgo You probably need to add a space after optics (see below):

```
cmd = "show interfaces diagnostics optics " + nni_port
print(cmd)
```

Otherwise your string concatenation would make it be:

`show interfaces diagnostics opticsge-0/0/0`

i.e. it would just merge optics and ge-0/0/0 together.

I would also construct `cmd` and print out to make sure you are sending a proper command down the channel, then use `send_command(cmd)` to send the cmd after you have verified it.

**Comment by elina89virgo** [comment]
I should have known better. Will be more careful in the future.
And a very good tip, appreciate that! 
Have a good week!
