### ISSUE TITLE
Genie for IOS and IOS-XE

### ISSUE THREAD

**Issue by ktbyers** [ktbyers/netmiko#1309]
Cisco has split the parsers here. When use_genie=True is set we might want to try both the IOSXE and IOS genie parsers and use the first one where structured data is returned.

This is mostly related to other libraries like NAPALM that might use Genie parsing and don't have any native differentiation between IOS and IOSXE and where it would be hard to add.

**Comment by micyew** [comment]
Does that mean I don't have to specify the OS when I set use_genie=True? ie. Netmiko will try both IOSXE and IOS? How about NXOS? Can Netmiko/Genie parse NXOS output? thanks..

**Comment by carlniger** [comment]
@micyew genie parsers -> https://pubhub.devnetcloud.com/media/genie-feature-browser/docs/#/parsers

You don't specify the OS on `send_command` because netmiko already knows what it is from when you create the connection object. Netmiko will only pass what you use -- thats Kirk's point here basically -- so you have to explicitly use the `cisco_xe` netmiko device_type if you want to have the right parser (for ios-xe devices) used. So we'll probably modify things to try both "regular" ios and ios-xe in the future so that things like NAPALM don't need to care about that distinction.

Examples [here](https://github.com/ktbyers/netmiko/tree/develop/examples/use_cases/case18_structured_data_genie)

**Comment by ktbyers** [comment]
This wasn't ever implemented--so you would need to specify the correct device_type to get Genie to work properly either `cisco_ios` or `cisco_xe` depending on what your device is.
