### ISSUE TITLE
concurrent connections to same wlc

### ISSUE THREAD

**Issue by imbouncin** [ktbyers/netmiko#1325]
Hi. 
Im trying to speed up my script.
One of my options is to make several concurrent connections to same wlc.
But im getting "OSError: Socket is closed" error
So my question is it possible to do with netmiko and if it is, which options should i add in my connection obj
    conn = {
        'device_type': 'cisco_wlc_ssh',
        'host': controller,
        'username': user,
        'password': password,
        'banner_timeout': 30
    }

**Comment by carlniger** [comment]
You would need to create a connection object per connection you want to open. Netmiko provides the ability to connect to things but if you want to spawn multiple connections/use threading/etc. you need to handle that on your own.

Going to close this since I don't think this is a netmiko issue/bug, but feel free to chime back in if I'm missing something. Also, feel free to join the Pynet slack community [here](https://join.slack.com/t/pynet/shared_invite/enQtNTA2MDI3NjU0MTM0LTQ5MjExNGNlNWIzMmRhOTZmNmZkNDA2Nzk4Y2Q1Y2RkMWNhZGEzM2Y5MjI0NDYxODkzM2M0ODIwYzFkMzVmZGY) where you can find a dedicated netmiko channel for general questions/discussion stuff!
