### ISSUE TITLE
Parser output with genie. Cisco NXOS. Cmd: "show cdp neighbors detail"

### ISSUE THREAD

**Issue by DaianaCasas** [ktbyers/netmiko#1330]
Hi , 
I stablish connection with a cisco nxos device. 
When i send the command "show cdp neighbors detail" with the genie option active, i get  a string output.  I have the same problem with the command "show running-config".
However, i get a parser output with others commands: 
- show version
- show vrf
- show ip route vrf <name_vrf>

Code:
device=connectHandler(**dev)
output =  device.send_command("show cdp neighbors detail", use_textfsm=False, use_genie=True)
print(ouput)
Somebody else have this problem?

**Comment by carlniger** [comment]
I highly doubt there is a genie parser for the running config. You should consult the list of genie parsers [here](https://pubhub.devnetcloud.com/media/genie-feature-browser/docs/#/parsers)

For the cdp neighbor issue, ensure you are typing the full command as that is passed to Genie to select the right parser. I just tested w/ `show cdp neighbors detail` and genie properly parsed the output (n9kv on recent code), but there may be some version dependent things there as well (you'd need to check genie docs for this type of thing though). Since this isn't a netmiko issue I'm going to close this.

Feel free to join the Pynet slack community [here](https://join.slack.com/t/pynet/shared_invite/enQtNTA2MDI3NjU0MTM0LTQ5MjExNGNlNWIzMmRhOTZmNmZkNDA2Nzk4Y2Q1Y2RkMWNhZGEzM2Y5MjI0NDYxODkzM2M0ODIwYzFkMzVmZGY) where you can find a dedicated netmiko channel for questions/comments/etc if you're still having any issues/want to chat w/ folks about this or anything else.
