### ISSUE TITLE
genie and nornir/netmiko failing with num_workers greater than one

### ISSUE THREAD

**Issue by salvapinyol** [ktbyers/netmiko#1347]
Hi team.

I'm using nornir with netmiko send_command and parameter use_genie = True.
If I run the tasks sequentially (configuring nornir num_workers = 1) genie parsing for all devices is fine. (I'm just parsing a show version command)
But if i try to enable multithreading (num_workers > 1) the genie parsing fails for some devices. The devices that fails on each run are different so is pretty random. 
I don't know if the problem is on genie side and not possible to fix in netmiko, but in that case maybe some warning could be added on netmiko documentation to make people aware.

Thanks

**Comment by ktbyers** [comment]
@salvapinyol There is just not enough information included here to provide any assistance.

If you have a particular device that failed and you post its exception stack we might be able to provide some help.

**Comment by salvapinyol** [comment]
ok, sorry for not providing enough information. I'll try to elaborate a bit more.

1.- I've a set of devices (cisco nxos) that executing netmiko send_command with use_genie = True for command "show version", the result is always structured data (it means that the genie parsing is working for ALL  the devices).
2.- I've created a nornir task to run the netmiko send_command to ALL the devices.
2.1- If I run the nornir task with num_workers = 1, the result of the show version for each devices is always structured data, so genie parsing is working fine.
2.2.- If I run the nornir task with num_workers > 1 (so using threads), the result of the show version for some of the devices is in form of raw text. So genie parsing is failing for some devices. If i try to run the task again the devices failing are others, but always some devices fails.

Due to how is implemented the genie parsing in netmiko I don't get any exception or error.  (that's why i didn't include it on the first post). Netmiko send_command tries to parse the output of the show version command via genie parsing and if it fails just return the raw ouput (text string) of the command.

After doing some debugging, it seems that the call to genie's get_parser function inside get_structured_data_genie fails in a random way when used with threads.

Thanks,

**Comment by carlmontanari** [comment]
What version of genie/pyats do you have installed. I've just tested against 6 hosts (w/ default num workers) we have handy w/ a very basic script and it works as expected -- structured output from all hosts. I've got genie 19.7, pyats 19.7, and nornir 2.2.0 installed -- what versions are you running? We'll probably need to see your script to see if anything sticks out there too.

**Comment by salvapinyol** [comment]
@carlmontanari, these are my versions:
pyats 19.8
genie 19.8
nornir 2.2.0
netmiko 2.4.1

I've attached a simplified version of the script (with just to devices) and the output of the script with workers =1 and workers > 1

[nornir_test_fail.py.txt](https://github.com/ktbyers/netmiko/files/3573055/nornir_test_fail.py.txt)

The output:
# with num_workers = 1
python nornir_test_fail.py -w 1
ES1SW55AUN6: parsing OK
ES1SW54AUN6: parsing OK

# with num_workers = 2 (first run)
python nornir_test_fail.py -w 2
ES1SW55AUN6: PARSING KO ####
ES1SW54AUN6: parsing OK

# with num_workers = 2 (second run)
python nornir_test_fail.py -w 2
ES1SW55AUN6: parsing OK
ES1SW54AUN6: PARSING KO ####

**Comment by carlmontanari** [comment]
I can't recreate the issue w/ your provided script; regardless of num workers things are just working for me. I replaced your inventory plugin w/ simple inventory, but no other changes. Here is what I ended up with:

```
    nr = InitNornir(config_file="config.yaml")
    nr = nr.filter(F(groups__contains="nxos"))
```

My config file just points to normal simple inventory host/group/defaults files.

Given all that, I don't really think this is a netmiko issue so I'm going to close this. I would suspect you have something (no idea what!) going on w/ your inventory plugin since your results both show things executing against the same switch twice. I'd give it a shot w/ simple inventory plugin just to see if that sorts things out. Lastly, would be worth checking the nornir logs and/or cranking up logging and sending that to stdout for troubleshooting purposes.

Feel free to join the Pynet slack community [here](https://join.slack.com/t/pynet/shared_invite/enQtNTA2MDI3NjU0MTM0LTQ5MjExNGNlNWIzMmRhOTZmNmZkNDA2Nzk4Y2Q1Y2RkMWNhZGEzM2Y5MjI0NDYxODkzM2M0ODIwYzFkMzVmZGY) -- there is a dedicated nornir channel (and netmiko) which is probably a better place for this!

**Comment by salvapinyol** [comment]
ok @carlmontanari, thanks for your time and advise. 

I've just found this on pyats documentation:

https://pubhub.devnetcloud.com/media/pyats/docs/async/versus.html

Warning

pyATS infrastructure is not thread-safe. If you must, use threads only on your own libraries and functions.

So I believe I'm not the only one that will run into problems with nornir/pyats.

Regards
