### ISSUE TITLE
Neither cleanup() nor disconnect() can remove the admin session from Palo Alto (7.1.13)

### ISSUE THREAD

**Issue by hyuxenanetworks** [ktbyers/netmiko#1353]
**First, I want to say this project is awesome. Love it.**

Before knowing this project, I am also writing a thin client to SSH Palo Alto firewalls but I have  encountered an issue that I cannot solve. Interestingly, I can also see the same issue with `PaloAltoPanosSSH `here. 

**The issue is:**
Usually on Windows, if you use Putty or Windows SSH client to log into Palo Alto and then `exit/quit`, the corresponding admin session will be removed from PANOS. You can use `show admins` to get the list of logged in admin sessions.

However, with` paramiko/netmiko`, no matter if you `cleanup()` or `disconnect()`, the admin session will remain until it is automatically timed out by PANOS. This means every time you connect to Palo Alto, you will leave a small "garbage" in the Logged In Admin, which to some people can be ugly. I've been fighting with this for some time but without any luck. I can see netmiko has the same problem. Do you have anything clue? I'll be willing to help and test.

**Below is my small test script:**
```
import netmiko

pa_3060 = {
    'device_type': 'paloalto_panos',
    'host': '192.168.1.168',
    'username': 'test',
    'password': 'test'
}

pa_3060 = netmiko.paloalto.paloalto_panos.PaloAltoPanosSSH(
    host='192.168.1.168',
    username='test',
    password='test'
)

output = pa_3060.send_command('show admins')
print(output)
# pa_3060.cleanup()
pa_3060.disconnect()
```
This is the output and you can see the accumulated admin sessions.
![image](https://user-images.githubusercontent.com/17590289/64344372-9cb84980-cfee-11e9-8230-ca689dca2005.png)

**Comment by carlmontanari** [comment]
@hyuxenanetworks thanks for the good issue!

When calling `disconnect` it should call the following function from the Palo Alto driver:

```
    def cleanup(self):
        """Gracefully exit the SSH session."""
        try:
            self.exit_config_mode()
        except Exception:
            # Always try to send 'exit' regardless of whether exit_config_mode works or not.
            pass
        self._session_log_fin = True
        self.write_channel("exit" + self.RETURN)
```

exit_config_mode also looks pretty reasonable:

```
    def exit_config_mode(self, exit_config="exit", pattern=r">"):
        """Exit configuration mode."""
        return super(PaloAltoPanosBase, self).exit_config_mode(
            exit_config=exit_config, pattern=pattern
        )
```

I assume, based on what you wrote that using "exit" to leave config mode then "exit" to disconnect/close session is accurate? Or do you need to explicitly call `quit` to close the session? 

Basically playing with these two functions in the Palo Alto driver would be what we'd need to test to ensure things are disconnecting properly. If what we have sounds reasonable/correct then it may be worth grabbing a session log to see what netmiko is seeing/doing. If it sounds like we're missing `quit` or some other command, replacing/adding to these functions as needed and retesting is probably the next step!

**Comment by carlmontanari** [comment]
Just tested this against 9.0.1 and w/ the current develop branch I do *not* see the stale sessions. I searched a little on this and it looks like the way to clear/remove stale sessions is to use the following command: `delete admin-sessions username SOMEUSER` -- I think we would very much not want this as you may have an admin session in the web UI as well as the CLI and if you clear sessions for a particular username it clears all of the sessions. I also looked around a bit to see if there was a "logout" option to more gracefully log out on older versions (I would assume just pre 9.x since its working as expected in 9.x) and I didn't see anything immediately obvious other than just "exit" which we're already doing. So I'm going to close this for now, but feel free to re-open if there is a good fix for this!

**Comment by hyuxenanetworks** [comment]
> Just tested this against 9.0.1 and w/ the current develop branch I do _not_ see the stale sessions. I searched a little on this and it looks like the way to clear/remove stale sessions is to use the following command: `delete admin-sessions username SOMEUSER` -- I think we would very much not want this as you may have an admin session in the web UI as well as the CLI and if you clear sessions for a particular username it clears all of the sessions. I also looked around a bit to see if there was a "logout" option to more gracefully log out on older versions (I would assume just pre 9.x since its working as expected in 9.x) and I didn't see anything immediately obvious other than just "exit" which we're already doing. So I'm going to close this for now, but feel free to re-open if there is a good fix for this!

This is also what I have found so far. Seems there is nothing much to do. Agree with you on closing this issue.

**Comment by vincemarinov** [comment]
Hey guys,
I had the same issue. The problem is that once you send the command, Netmiko is not validating if the command was taken so you have to tell it that after the command was sent it is now in the initial position. For that I have added expect_string = "". The following code works for me  :

# Here we are exiting config mode
exit_output = net_connect.exit_config_mode()

# Here we are exiting from Panorama by se3nding the "exit" command
exit = net_connect.send_command("exit", expect_string = "")

Regards

**Comment by ktbyers** [comment]
@vincemarinov The issue you are referencing was closed over 3 years ago. You should open a new issue and indicate what you are seeing.

I did not follow what you are stating above so you will need to provide additional details.
