### ISSUE TITLE
I got OSError: Search pattern never detected in send_command_expect 

### ISSUE THREAD

**Issue by holytanx** [ktbyers/netmiko#1428]
Hello, 
I apologize in advance for my English and question too, after I couldn't find answer from Google.

I have two routers
```
router1={
    'device_type':'cisco_ios',
    'ip':'10.10.10.6',
    'username':'network',
    'password':'cisco',
}
router2={
    'device_type':'cisco_ios',
    'ip':'10.10.10.7',
    'username':'network',
    'password':'cisco',
}

routers = [router1,router2]
```

so i tried to use write memory command
```
for r in routers:
            net_connect = ConnectHandler(**r)
            net_connect.enable()
            output = net_connect.send_command('write mem')
            print(output)
```

I got this error after trying to write memory:
```
  File "C:\Users\world\Desktop\pp\config_router.py", line 60, in setup_interface
    net_connect.send_command('write mem')
  File "C:\Python\Python37-32\lib\site-packages\netmiko\base_connection.py", line 1337, in send_command
    search_pattern
OSError: Search pattern never detected in send_command_expect: R1\#
```

**Comment by carlmontanari** [comment]
Couple things that may or may not be the issue/fixes:

If you just SSH to the device as the user here and type enable do you get prompted for a password? Generally if you are needing to send `enable` (using the `.enable()` method) you would need to add the `secret` argument (enable secret password) to the device you pass to ConnectHandler. 

Since you are working with Cisco IOS, you can use the `save_config` method instead of manually doing it yourself -- this may just save you some hassle.

For troubleshooting this I would just try to connect to one device at a time and get rid of the loop -- generally this would just make things easier to diagnose.

Lastly, it may be helpful to add the `session_log` argument to the ConnectHandler so you can see what is going on a little better.

**Comment by carlmontanari** [comment]
I'll go ahead and close this, but feel free to reopen if this is still an issue. 

Also, you are welcome to join the Pynet slack community [here](https://join.slack.com/t/pynet/shared_invite/enQtNTA2MDI3NjU0MTM0LTIyZDdhMTBlOWNmNDJhNjkxZTEyMDg3NTRkOWIxMTUwOTAzYmQ0ZjMwMGMyNTM4N2E1YzA3YWQ1MWFiOWM1YzU) where you can find a dedicated netmiko channel for questions/comments/etc if you're still having any issues.
