### ISSUE TITLE
Multiple Configuration Modes #56 (Juniper)

### ISSUE THREAD

**Issue by isriam** [ktbyers/netmiko#1434]
Is it possible to add 'config_mode' as a variable in juniper.py?  I had to change the config_command to 'configure private' since i wasn't able to change the mode on send_command().

thanks!

**Comment by carlmontanari** [comment]
You can already use the `config_command` argument on `send_config_set` method, so I believe this should just work. 

See `send_config_set` [here](https://github.com/ktbyers/netmiko/blob/develop/netmiko/base_connection.py#L1608)

And the Juniper `config_mode` method [here](https://github.com/ktbyers/netmiko/blob/develop/netmiko/juniper/juniper.py#L74)

Going to close since I think this is a non-issue, but feel free to comment/re-open if I'm missing something.

**Comment by isriam** [comment]
thanks, i'm a python newbie and i tried something like this but couldn't get the right syntax:

device.send_config_set(spe_filter, exit_config_mode=False, config_command="configure private")

**Comment by carlmontanari** [comment]
I think you are looking for `config_mode_command` there in your example!

**Comment by isriam** [comment]
actually i think this is the correct syntax right?

device.send_config_set(spe_filter, exit_config_mode=False,config_mode_command="configure private")
