### ISSUE TITLE
Regarding Netmiko Logging for multiple devices

### ISSUE THREAD

**Issue by pes2017** [ktbyers/netmiko#1436]
I want to enable Debug on multiple devices and log the output to different files. 
I saw the instructions in the link below and successfully Logging on a file.
but I want to output it separately on each device. 
Any help would be greatly appreciated.

https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md

import logging
logging.basicConfig(filename='test.log', level=logging.DEBUG)
logger = logging.getLogger("netmiko")

**Comment by carlmontanari** [comment]
You can add a `session_log` parameter when you instantiate a connection object. The session log won't have the full repr output of everything but would have all the reads/writes of the session.. so output like below:

```
3560CX#
3560CX#terminal length 0
3560CX#terminal width 511
3560CX#
3560CX#show run
Building configuration...

Current configuration : 7202 bytes
!
! Last configuration change at 17:25:05 PDT Mon Oct 21 2019
!
version 15.2
```

Because you are setting that per device you can of course just have multiple named log files "device1.log", "device2.log" etc.

I don't believe that you'll be able to (at least easily) achieve this with the built in python logger (at least the way it is currently setup).

**Comment by carlmontanari** [comment]
Going to close this. Feel free to reopen if there is any follow up conversation needed.

Also, please join the Pynet slack community [here](https://join.slack.com/t/pynet/shared_invite/enQtNTA2MDI3NjU0MTM0LTIyZDdhMTBlOWNmNDJhNjkxZTEyMDg3NTRkOWIxMTUwOTAzYmQ0ZjMwMGMyNTM4N2E1YzA3YWQ1MWFiOWM1YzU) where you can find a dedicated netmiko channel for questions/comments/etc if you're still having any issues.
