### ISSUE TITLE
ARP-like issue with ConnectHandler

### ISSUE THREAD

**Issue by dwoititz** [ktbyers/netmiko#1492]
Good day!

I have created a script that is to deliver code to 9 machines. Running the script one time, it is to ssh into each machine, deliver the code and go onto the next.

The first time I run the script there is an error at device 1. The second time I run the code device 1 is successful and there is an error at machine 2. The next time device 2 is good at the error at device 3. This continues until device 9.

Please see attached output.

Thanks!
[Netmiko Error Log.docx](https://github.com/ktbyers/netmiko/files/3984131/Netmiko.Error.Log.docx)

**Comment by carlmontanari** [comment]
I'd recommend a quick read through of [this](https://pynet.twb-tech.com/blog/automation/netmiko-what-is-done.html) post from Kirk. Helps to explain a lot of the workings of Netmiko. Given that you are seeing `timed out reading data channel` I'd suspect you can just increase the global delay factor to give the device(s) more time before Netmiko times out. I'm going to close this as I don't think it's a bug/issue, but feel free to reopen if that doesn't sort things out -- but please post your stack trace in formatted text here instead of attachments.

Join us in the Pynet slack community [here](https://join.slack.com/t/pynet/shared_invite/enQtNTA2MDI3NjU0MTM0LTIyZDdhMTBlOWNmNDJhNjkxZTEyMDg3NTRkOWIxMTUwOTAzYmQ0ZjMwMGMyNTM4N2E1YzA3YWQ1MWFiOWM1YzU) where you can find a dedicated netmiko channel for questions/comments/etc -- generally a better place for questions (GitHub is generally better for bugs/feature work).

**Comment by dwoititz** [comment]
Hi Carl, Kirk and Everyone,



Happy Holidays!



Carl,



Thank you so much for your quick and useful reply. Changing the global delay factor to 2 solved the issue.



Kindest regards,

Danny Woititz
CCIE Written (Lab exam pending)
CCNP R&S
CCNA Security
CCDA (Design)

On December 19, 2019 at 11:06 PM, Carl Montanari <notifications@github.com> wrote:



I'd recommend a quick read through of this post from Kirk. Helps to explain a lot of the workings of Netmiko. Given that you are seeing timed out reading data channel I'd suspect you can just increase the global delay factor to give the device(s) more time before Netmiko times out. I'm going to close this as I don't think it's a bug/issue, but feel free to reopen if that doesn't sort things out -- but please post your stack trace in formatted text here instead of attachments.

Join us in the Pynet slack community here where you can find a dedicated netmiko channel for questions/comments/etc -- generally a better place for questions (GitHub is generally better for bugs/feature work).

**Comment by dwoititz** [comment]
PS I joined the Pynet slack community per your suggestion

Thank you,

Danny Woititz

*This message was created on a hand-held device. Please forgive any typos.
