### ISSUE TITLE
how to cross cisco super mode?

### ISSUE THREAD

**Issue by MikeSiss** [ktbyers/netmiko#1496]

**Comment by carlmontanari** [comment]
Going to close this as there is.... nothing here. If you have a bug to report please open an issue with code/stack trace/relevant information; otherwise best place for general questions is on Slack [here](https://join.slack.com/t/pynet/shared_invite/enQtNTA2MDI3NjU0MTM0LTIyZDdhMTBlOWNmNDJhNjkxZTEyMDg3NTRkOWIxMTUwOTAzYmQ0ZjMwMGMyNTM4N2E1YzA3YWQ1MWFiOWM1YzU) where you can find a dedicated netmiko channel for questions/comments/etc -- generally a better place for questions (GitHub is generally better for bugs/feature work).
