### ISSUE TITLE
Script to apply the port-security directive on Cisco devices

### ISSUE THREAD

**Issue by Shaguu** [ktbyers/netmiko#1498]
Hello,

I am really new to python / netmiko but that interests me a lot.
I would like to deploy a configuration on my Cisco equipment on the  VLAN 130.
I have based myself on examples found here but I'm not sure what to do next :

```
!/usr/bin/env python
from netmiko import ConnectHandler
#from getpass import getpass
from ciscoconfparse import CiscoConfParse

device = { 
    'device_type': 'cisco_ios',
    'ip': '192.168.32.125',
    'username': 'myuser',
    'password': 'mypass',
    'fast_cli': True,

} 

net_connect = ConnectHandler(**device)
net_connect.enable()

run_config = net_connect.send_command("show run")
run_config = run_config.splitlines()
cisco_cfg = CiscoConfParse(run_config)
#cisco_cfg = CiscoConfParse("cisco.cfg")
config_obj = cisco_cfg.find_objects_w_all_children(parentspec=r"^interface",
                                                  childspec=[r"switchport access vlan 130"])
for parent in config_obj:
    print(parent.text)
   
```
In this way, I see my interfaces correctly. Now, I don't understand how to apply the following configuration (with  net_connect.send_config_set) on these interfaces :

```
switchport port-security
switchport port-security mac-address sticky
switchport port-security violation  restrict
switchport port-security aging time 15
```

and at the global configuration level :

```
snmp-server enable traps port-security
snmp-server host mymonitoringserver public
```
Could you guide me?

Many thanks,

Shaguu

**Comment by carlmontanari** [comment]
Will answer here just to close this out, but also saw your post on slack. In the future questions like this are probably best in slack -- and issues can be used for bugs/feature enhancement discussion and stuff like that.

To answer your question: the `send_config_set` method accepts a list of strings or a single string to send to the device. So instead of printing out the `parent.text` (which I am assuming is the config you are wanting to push) you could pass that to `send_config_set` method. Alternatively (if you had other config stuff you wanted to add or you didn't want to send the config at that point) you could just create a list and append the `parent.text` into the list -- leaving you with a list of configs to send whenever you want.

In either case, sending the config would just look like: `net_connect.send_config_set(SOMETHING)` where "SOMETHING" is your config string or list of config strings.

You can see the source for `send_config_set` [here](https://github.com/ktbyers/netmiko/blob/develop/netmiko/base_connection.py#L1637) if you were curious.
