### ISSUE TITLE
Add ability to pass a list of show commands

### ISSUE THREAD

**Issue by lykinsbd** [ktbyers/netmiko#1506]
There are frequently questions asked in online forums of how best to send a list of separate `show` type commands to a device with Netmiko.  Today there are two methods:

1. Utilize `send_config_set()`, which is less than ideal, because of two reasons.  First, it requires the user to have write access to the device, and second it will attempt to issue the commands in the configuration mode which potentially will not function depending on the network device vendor/platform.
2. Utilize a looping construct in Python to iterate over the list of commands and issue individual `send_command()` and return the output.  While this is commonly used, having every user of Netmiko re-invent the wheel is less than optimal.

Ideally, there would be another method such as `send_command_list()`, that accepted a sequence of Str and issued the commands itself.  It would then return a Dict with the command string as the key, and the output of those commands in strings as the value.

I have implemented something similar to this here: https://github.com/lykinsbd/naas/blob/master/naas/library/netmiko_lib.py#L24

While not directly applicable for upstreaming, the general idea is there and can form the basis of a `send_command_list()` method.  I can look at creating a PR for this later this week.

**Comment by daanvdsanden** [comment]
> Ideally, there would be another method such as send_command_list(), that accepted a sequence of Str and issued the commands itself. It would then return a Dict with the command string as the key, and the output of those commands in strings as the value.

It would be great if the dict values are the result of the send_command function. So the TextFSM integration is still there. And these parameters are passable to the function.

**Comment by ktbyers** [comment]
So I am pretty lukewarm on doing this--mainly because you get into all sorts of complexity related to argument passing to the underlying send_command.

For example, how do you indicate the termination of each individual command. Do we support a expect_string_list? Do we support TextFSM and Genie, as was referenced above (and does it apply to all commands)?

Do we try to strip the command echo and trailing prompt as send_command typically does? This is much less useful if you are handling multi-line prompting (i.e. when you are doing a single command and the router prompts you for additional things).

These complexities then get multiplied across Netmiko's set of 50+ platforms and potential confusion it causes users.

So I have a definite preference to just say use `send_command` or `send_command_timing` and a for-loop.

**Comment by ktbyers** [comment]
I am warming a bit to the idea of building a method `send_command_list`

Take `expect_list` as an argument. Support all of the other arguments of `send_command` besides `expect_string` (i.e. this would have to come from `expect_list`).

Return a dictionary of results:

key ---> the command set
value ---> the send_command response corresponding to that key.

**Comment by lykinsbd** [comment]
If you’re open to it, then I’ll work on a PR this week.

**Comment by ktbyers** [comment]
@lykinsbd Sounds good.

**Comment by ktbyers** [comment]
This is done in Netmiko 4.x with send_multiline and send_multiline_timing.
