### ISSUE TITLE
netmiko/TextFSM How to detect the difference between a parsing error and an empty result

### ISSUE THREAD

**Issue by 991jo** [ktbyers/netmiko#1558]
Hello

I have a command and a TextFSM template that parses that output. In my case this is the list of ssh keys installed on a device. The output can be empty if no keys are installed.

If I parse that with netmiko then I will get parsed result if there are ssh keys.
If there are no ssh keys I would like to get an empty list.
But if I understand that correctly netmiko checks if the output is an empty list and if it is it returns the raw output of the command which is a string.
This should be in https://github.com/ktbyers/netmiko/blob/995fdb8cf52dbf6ae80efb803e4a062674b70aa4/netmiko/utilities.py#L244-L256

As far as I can see it there is no difference between a TextFSM parsing error and a correctly parsed but empty result.

Is there a way to get an empty list back if that is a plausible output?

**Comment by ktbyers** [comment]
Wouldn't you just get an empty string in the case you describe? So wouldn't you already know the result?

**Comment by 991jo** [comment]
not necessarily.
IOS XR usually prints a timestamp for every command. But commands could also return some kind of "no contents" messages.

**Comment by ktbyers** [comment]
I just don't think I would change this behavior in Netmiko (i.e. I think the current behavior is the behavior I would want for when integrated into a `send_command/send_command_timing` call) and I wouldn't want additional arguments in send_command to override the default behavior.

The above is a function so you could possibly write your own modified version of the function to change the behavior. Of course there is additional textfsm glue-code than just this function so that would make it more complicated.

**Comment by 991jo** [comment]
So you suggest, that I make my own fork of netmiko and fix that there?
I dont think that it is to much work to add an additional argument to `send_command/send_command_timing`. I could take a look at it and make a pull request if the problem is the amount of work that has to be put into that.

**Comment by ktbyers** [comment]
You wouldn't need a fork (as that would cause longer term maintenance problems for you).

It is just a function i.e. you should be able to do implement it outside of Netmiko and just call it in your function. I haven't reviewed some of the intermediate code between that `_textfsm_parse` so there might be some additional code in their that is problematic...but from memory the code to get TextFSM to parse a given output is pretty small so I don't think it should be that difficult.

**Comment by ktbyers** [comment]
Yeah, I won't add an argument to send_command/send_command_timing for this.

You also need to remember the code is trivial--the documentation, testing/test code, and maintenance is not.

The place I might be convinced to add an argument would be in that above `_textfsm_parse`. I guess the other place I might be convinced to change the behavior would be to raise an exception for failed textfsm lookups in some way.

**Comment by 991jo** [comment]
raising an exception when the parser raises one would be fine. This would make it possible to distinguish between a parsing error and "empty" output.

**Comment by ktbyers** [comment]
Okay, do you want to do a PR on this?

**Comment by 991jo** [comment]
want to: yes, but currently I am not sure if I can offer more of my work time for that since I have a workaround for my case. Not nice but it works.

**Comment by demakkar** [comment]
I am facing this same issue where if textfsm match is not found it returns a complete output which is string instead of list of dictionaries..


('router bgp 64840\n'
 '   neighbor ghjj peer-group\n'
 '   neighbor ghjj  maximum-routes 12000\n'
 '   !\n'
 '   vrf corp\n'
 '      router-id 1.1.1.1\n'
 '      neighbor 10.116.124.242 peer-group hjkhk\n'
 '      neighbor 10.116.124.242 remote-as 5678\n'
 '      neighbor 10.116.124.242 fall-over bfd\n'
 '      neighbor 10.116.124.242 description '
 'fghj\n'
 '      neighbor 10.116.124.242 soft-reconfiguration inbound\n'
 '      neighbor 10.116.124.242 route-map abc '
 'in\n'
 '      neighbor 10.116.125.66 peer-group azure-msee-all\n'
 '      neighbor 10.116.125.66 remote-as 12076\n'
 '      neighbor 10.116.125.66 fall-over bfd\n'
 '      neighbor 10.116.125.66 description '
 'rtyu\n'

**vs** 

[{'aggnetwork': '20.0.0.0/8',
  'localnetwork': '10.0.0.0/8',
  'matchmap': 'def',
  'routemap': 'abc'},
 {'aggnetwork': '20.0.0.0/8',
  'localnetwork': '',
  'matchmap': 'ghi',
  'routemap': ''},
 {'aggnetwork': '',
  'localnetwork': '10.224.14.26/31',
  'matchmap': '',
  'routemap': 'qui-hlb-snat'}]

**Comment by Kircheneer** [comment]
I think there is still an issue here. Going back to the original point. If I have a `show vlans` output from a device without any VLANs, I _want_ an empty list returned, not the original raw output. Parsing has succeeded and as such the parsed data (empty list) should be returned.

I encountered this during my work here https://github.com/ktbyers/netmiko/pull/3406

The proposal would be to change 

```
if structured_data == []:
    return raw_output
else:
    return structured_data
```

to

```
return structured_data
```

[here](https://github.com/Kircheneer/netmiko/blob/04f2530e460d90fae0503274944cfcfcd0c1917e/netmiko/utilities.py#L347)

This would of course be a breaking change.

Are there valid use cases for the current behaviour?

**Comment by Kircheneer** [comment]
Summary of my conversation on Slack with @ktbyers:

It is template-dependant whether an empty template can be assumed to be a valid parsing result or a parsing error. With [ntc-templates](https://github.com/networktocode/ntc-templates), most and all new templates properly raise errors, but you can write TextFSM templates where this is not the case. Thus, the behavior from #3406 is the correct way of handling it. In case you know that your templates raise errors properly and return empty lists only when desired, you can simply catch the new `NetmikoParsingException` there and then assume an empty list.
