### ISSUE TITLE
Support for Huawei MA5680T OLT

### ISSUE THREAD

**Issue by markom84** [ktbyers/netmiko#1620]
Will it be possible to add support for this kind of device?
At the moment netmiko times-out. Upon inspection of session_log, it gets stuck at:

MA5680T-H01>screen-length0temporary
            ^
  % Unknown command, the error locates at '^'

MA5680T-H01>

Proper command for that would be: 'scroll 512' (512 is maximum number of lines supported, there is no 0)

Also, MA5680T has 'enable' mode, config_mode is not 'system-view', but it's 'config'

There are more things that differ from Huawei routers, compared to driver in netmiko, i have access to this device, so I would be willing to help if needed.

**Comment by ktbyers** [comment]
@markom84 You would need to create a driver for it. The process for creating a driver is detailed here:

https://github.com/ktbyers/netmiko/blob/develop/VENDOR.md

**Comment by BSpendlove** [comment]
Hey @markom84 I'm actually working on a driver and have implemented all of this (enable mode, config mode, send_command) etc...

There are some bad problems that occur because you can't disable the paging, such as when using `display current-configuration`, you need to get netmiko to handle the SSH output to send a space if `--- More` is found. Or when you send a command, Huawei typically prompts something like:

`{ <cr> | <example1> | <example2> }`

Which you can manually write to the SSH channel a \n, but it's better to let Netmiko handle it, I'm getting far with implementing the driver and handling the awful implementation that Huawei have on the SmartAX devices 😂

**Comment by ktbyers** [comment]
I commented on this issue here:

https://github.com/ktbyers/netmiko/issues/1628

**Comment by Fikirsiz** [comment]
I added support for Huawei OLT in #1642, please test it.

**Comment by ktbyers** [comment]
SSH support for OLT was added here:

https://github.com/ktbyers/netmiko/pull/1654

Thanks to @Fikirsiz for work he did on testing SmartAX driver with OLT.

**Comment by Salinas2k** [comment]
Hey @BSpendlove, Im doing a new driver for this model, a little bit hard but we still on it. I want to comment that there is a function in config mode that returns all output at once. it is `mmi-mode original-output` you can try it.

**Comment by BSpendlove** [comment]
@Salinas2k hey, nice to hear, I think my merge request got accepted and is now in the netmiko production version... Managed to fix that output by setting "undo smart" upon logging into the device, something like that... I've been using like that in production for the past few months and it works perfectly!

**Comment by Salinas2k** [comment]
Nice! :)
