### ISSUE TITLE
Send_config_set with except_string issue in Hpe comware switch

### ISSUE THREAD

**Issue by vkazimov** [ktbyers/netmiko#1722]
Hi.
How can use except_string with send_config_set command?
command = ["system-view", "interface gigabitethernet1/0/1", "default", "Y"]
output = net_connect.send_config_set(command)
print(output)

For example (in Hpe comware switch)
` <HPE_5130SW>system-view
System View: return to User View with Ctrl+Z.
<HPE_5130SW]interface gigabitethernet1/0/6
[HPE_5130SW-GigabitEthernet1/0/1]default

This command will restore the default settings. Continue? [Y/N]:  Y`

**Comment by ktbyers** [comment]
You can't with send_config_set(). The expectation with send_config_set() is that there is no additional prompting.

To handle the config + prompting scenario, you would need to do:

```python
output = net_connect.config_mode()
output += net_connect.send_command_timing("interface gigabitethernet1/0/6")
output += net_connect.send_command_timing("default")
if 'Continue' in output:
    output += net_connect.send_command_timing("Y")
output += net_connect.exit_config_mode()
```    

That should be pretty close. You could also use `send_command` and the `expect_string` argument instead of `send_command_timing`
