### ISSUE TITLE
Patternless prompt_detection without depending on delay values.

### ISSUE THREAD

**Issue by jonathanslenders** [ktbyers/netmiko#1830]
Opening this issue here for awareness. I understand if this is not going to end up in Netmiko.

I've been experimenting with an alternative way of prompt detection which does not rely on timers, but instead probes for line editing capabilities that are only present when a prompt is displayed.

It means that we can read as fast as possible, but we are 100% positive when we hit a prompt. I have a working proof of concept that I shared in the Scrapli issue tracker:
https://github.com/carlmontanari/scrapli/issues/30

Probably we have to test on more devices to be sure this works everywhere, but if it does, it could be a nice performance boost for Netmiko.

**Comment by ktbyers** [comment]
Adding some more thoughts/comments. I also commented slightly on the scrapli issue tracker:

How would multi-line prompting work? I.E. things like `confirm [y/n]`?

I would be worried/concerned (in a Netmiko context), how reliably I could count on `cntl-a` and `cntl-k` to work across 70+ platforms (and I wouldn't really have a reasonable way of regression testing if they did in fact work or not nor of finding an alternate pattern that did work)?

Why would it make it any faster at detecting the prompt compared to a regex pattern? I would think it would actually be slower (though it might let you avoid the false-positive problem when the output actually has '#' or '>' in it).

Also I would get worried that it is going to cause problems with the output as now you need to strip out all the `prompttest` messages and ANSI codes and backspaces from the output. Though maybe this is easy enough since it is a single pattern (so this probably goes back to how well the 70+ platforms support a standard behavior here).

**Comment by jonathanslenders** [comment]
> I would be worried/concerned (in a Netmiko context), how reliably I could count on cntl-a and cntl-k to work across 70+ platforms

That's a fair question. - I don't know. There are alternatives, like probing for support of left/right arrows, which render into things like ``^[[D``. If the remote side doesn't support any line editing capabilities, then this doesn't work.

For the ``confirm [y/n]``, this is tricky. I assume this doesn't require an ENTER key press after the "y" or "n", right? The only way to probe for this is that nothing gets rendered on key strokes like ``ctrl-a`` or ``ctrl-k``. But that doesn't work, because it is always possible that the output is still coming, so then we're back to timeouts.

I think the main advantage for this proposal is mainly for situations where ``>`` appears in the output, and when we are waiting for an interactive prompt. 

Maybe it is not faster. I was assuming that for some situations we can't rely on regex patterns, and there we use timeouts. This approach does not require any timeouts.

Filtering out the probing strings can be done reliable.

The problems are indeed as you stated: whether all devices support line editing, and whether it works with these confirm prompts.
