### ISSUE TITLE
Older Arista EOS devices fail on set terminal width

### ISSUE THREAD

**Issue by zeushammer** [ktbyers/netmiko#2066]
Hi @ktbyers - you are bombarded with questions and give your all to the community. If you can set me and my team straight I'll donate an hour of my wages for your time if you can point me to your donation collections tin car ;) 

Here is our test code

```python
from netmiko import ConnectHandler
import logging

logging.basicConfig(filename='/home/gears/test.log', level=logging.DEBUG)
logger = logging.getLogger("netmiko")

device = {
    'host': 'zeushammer.net',
    'username': 'zeus',
    'password': 'hammer',
    'device_type': 'arista_eos_ssh',
    'allow_auto_change': True
}

net_connect = ConnectHandler(**device)
net_connect.disconnect()
```

My team sees two types of responses intermittently. Sometimes from the same host where the code had previously just worked.

[Here is a gist of the log output where it failed](https://gist.github.com/zeushammer/be4f7168effecef05cb3fc73fa442001)
[Log output where it worked](https://gist.github.com/zeushammer/6f458832a44797dd923dc7123b783653)

Can you help us understand the logs, why one failed vs succeeded and what we can test to improve things?

**Comment by ktbyers** [comment]
@zeushammer Sorry for the delayed response...

So the `failed case` looks like this to me:

Netmiko early in the SSH session expects to send `terminal width 511` command and to see back a `Width set` message (it looks like we never see the `Width set` message):

# This is from my device
```
arista1#terminal width 511
Width set to 511 columns.
```

I could probably tell more definitely if you send over the full exception stack trace.

I know certain very old versions of EOS don't support some aspect of this terminal width command (or its response) so that is one possibility, but in that case it should fail every time.

If it fails intermittently, then that starts to sound more like a timing issue. I would probably try setting `fast_cli=False` and see if that fixes the problem (albeit operating much slower).

Let me know if this works/helps.


Regards,

Kirk

**Comment by zeushammer** [comment]
Thanks Kirk,

Here is what we found. When we bypass `set_terminal_width`
https://github.com/ktbyers/netmiko/blob/dec/netmiko/base_connection.py#L1099

And instead use the code below:

```
...

net_connect = ConnectHandler(**device, fast_cli=False, auto_connect=False)
net_connect.establish_connection()
net_connect.disconnect()

...
```

Everything is working successfully! What information do you need from our team to help you or help us create a patch?

**Comment by zeushammer** [comment]
In addition - here is the debug log from the successful run.

https://gist.github.com/zeushammer/7937209bdf35618061cad41841b8b657

**Comment by ktbyers** [comment]
@zeushammer Can you just include the CLI output of a failing device for the following:

```
terminal width 511
```

In other words, when you manually execute the following from the CLI what does the Arista device show/echo to the screen.

Probably easy way for a donation is just PayPal. If you want to do this, just let me know.


Regards,

Kirk

**Comment by zeushammer** [comment]
Of course yes! I do want to donate.

The output is what expect is looking for.

Exactly as sent.

We see it manually, but it's not seen via netmiko.

I'll confirm with the team tomorrow to grab the exact copy/paste verbatim.

**Comment by ktbyers** [comment]
Paypal is `ktbyers@twb-tech.com` (if you donate let me know, so we check/monitor it on our side).

Best, Kirk

**Comment by ktbyers** [comment]
@zeushammer Did you ever get this working?

Very old issue, so I am going to close this. If it is still an issue that is actively being worked on, let me know and I will re-open it.
