### ISSUE TITLE
ConnectHandler vs BaseConnection?

### ISSUE THREAD

**Issue by T2evh** [ktbyers/netmiko#2085]
I have a Cisco IOS switch which I can't telnet to using ConnectHandler but if I change the call to BaseConnection it works. The parameters for each are the same. I assume I should use ConnectHandler, but it fails for this particular switch. Any suggestions?

connection = netmiko.BaseConnection(ip='***',device_type='cisco_ios_telnet',username='***',password='***',port=23)
CONNECTS!

connection = netmiko.ConnectHandler(ip='***',device_type='cisco_ios_telnet',username='***',password='***',port=23)
FAILS!

I've many switches were BaseConnection works, it's just this one switch.

Thanks

**Comment by ktbyers** [comment]
Using `BaseConnection` is not valid/supported so it is just a bit of luck that it works on that one switch. It is possibly due to differences in the telnet_login method in BaseConnection versus the one that is used for cisco_ios_telnet.

Anyways, in order to fix the underlying problem, you would need to post the exception stack on the ConnectHandler call. Also is there anything unusual about this switches telnet (as far as prompts or slowness)?
