### ISSUE TITLE
Character Encoding

### ISSUE THREAD

**Issue by lipanpan65** [ktbyers/netmiko#2603]
cmd = [
        ...
        'description 中文中文中文中文中文中文中文中文中文中文中文中文中文中文中文中文中文中文中文中文中文中文中文中文',
        ]

When I operate the Huawei firewall, if my command contains relatively long Chinese. Will report an error. Character encoding is gb2312,If the Chinese is relatively short, there will be no such problem

![image](https://user-images.githubusercontent.com/61178683/144546724-9fe018c1-9ffe-4d07-9582-0b2cdadaa2d5.png)

**Comment by ktbyers** [comment]
Which Netmiko version are you using?

There is an encoding argument you can specify as an argument to ConnectHandler. You probably would have to research in the Python community whether there is any way to make this "gb2312" character encoding.

What are you setting for the value of `encoding` (in the ConnectHandler arguments)?

**Comment by jiujing** [comment]
@ktbyers 
we can character encoding in initial process，but when we read from channel，I found ，it does not work.Because it is "utf8" .In my opinion,it will be better if it is "self.encoding"   。
This occurs in netmiko version 3 and version 4. 
![image](https://user-images.githubusercontent.com/24587178/177336407-1a3078dd-ce09-45e7-aa36-84a6522a26c2.png)

**Comment by ktbyers** [comment]
@jiujing Proposed fix here:

https://github.com/ktbyers/netmiko/pull/2847

Just let me know if this doesn't work or if you run into issues here.
