### ISSUE TITLE
read_timeout ignored

### ISSUE THREAD

**Issue by c3101** [ktbyers/netmiko#2667]
When using "send_command" with a "read_timeout" specified, netmiko seems to comfortably ignore the read_timeout value and return incomplete output

```
# LETS GET THE START-UP CONFIG
print(f"{FirewallHostName}: Getting startup config")
start = time.time()
output = fw_con.send_command("show startup-config", read_timeout=360)
end = time.time()
elapsed = end - start
print(f"{FirewallHostName}: That took {elapsed} seconds")
print(f"{FirewallHostName}: writing startup-config file")
```

script output:
```
my_firewall: Getting startup config
my_firewall: That took 14.80399465560913 seconds
my_firewall: writing startup-config file
```

and the value of ```output``` is incomplete and not the entire output as expected from ```show startup-config```

```delay_factor``` seems to display similar behavior

**Comment by ktbyers** [comment]
@c3101 Are you using Netmiko `develop` branch? `read_timeout` is only supported on the `develop` branch?

Also can you include the debugging log?

https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel

**Comment by ktbyers** [comment]
Which Netmiko device_type are you using?

How long (roughly) does the command take if you execute it manually in an SSH session?

Can you post the full exception stack trace?

On Netmiko 3.4.0, in order to increase the Netmiko delay you would need to set the following:

```
fast_cli = False,
global_delay_factor=2
```

Alternatively, you could pass in delay_factor=2 to send_command(), but once again fast_cli has to be set to False. 

fast_cli is a ConnectHandler argument.

Either delay_factor=2 or global_delay_factor=2 should give you a up to 200 seconds for send_command() to complete (assuming fast_cli=False).
