### ISSUE TITLE
Cisco IOS Catalyst can contain device hostname# in self-signed certificate thus breaking send_command

### ISSUE THREAD

**Issue by zohassadar** [ktbyers/netmiko#2742]
My problem has been worked around, but posting in case this helps others with a similar issue.

Running python 3.10.3, netmiko 4.0.0

The issue was observed on about a dozen devices, all one of the following platform/version:

Catalyst C3560G running 15.0(2)SE9
Catalyst C2960s running 15.2(2)E9

`session` instantiated with `ConnectHandler(host=host, username=username, password=password, device_type="cisco_ios")`

The symptom is the result of `session.send_command("show startup-config")` comes back incomplete.  In all problem cases, 20,000 bytes (at least) of config is expected, but only the first 7,000 bytes or so is returned.  The cutoff seems arbitrary and doesn't necessarily occur at a line break.  There's no delay and the incomplete result comes back quickly.  

The cause is the name of the self signed certificate in the config.  Here's a santized example:

```
!
hostname DEVICE123
!
<omitted for brevity>
!
crypto pki certificate chain TP-self-signed-1234567890
 certificate self-signed 01 nvram:DEVICE123#1.cer
```

In the method `send_command` for the class `BaseConnection` in `base_connection.py`:

```
                else:
                    if len(output) <= MAX_CHARS:
                        if re.search(search_pattern, output):
                            break
```
Code [here](https://github.com/ktbyers/netmiko/blob/develop/netmiko/base_connection.py#L1672)

The default value of `search_pattern` (in this case would be `DEVICE123\#`) ends up matching the name of the certificate, causing the break to occur prematurely.

The workaround I'm using is to send the prompt to `expect_string` but with the multiline flag enabled and a start of line anchor prepended.  

```
anchored_prompt = '(?m)^' + re.escape(session.find_prompt().strip())
show_start = session.send_command('show startup-config', expect_string=anchored_prompt)
```

I don't know why these devices use the hostname in the certificate name instead of the much more common `nvram:IOS-Self-Sig#1.cer`, but in all cases the trust point name matches what looks like the system generated name.  I have no clue if it's a widespread enough of a problem to be worth solving for all potential cases.  

In previous versions of netmiko and before digging into the root cause, I worked around by disabling fast_cli and increasing the delay_factor.

**Comment by ktbyers** [comment]
Yeah, the fundamental question to me is why is the `hostname#` in the certificate name? That really should be avoided at all costs with CLI automation.

So that would be what needs to be dug into i.e. what situations cause that and how it can be avoided.

On the face of, I would have expected this to fail on earlier versions of Netmiko (i.e. Netmiko should have been looking for the prompt as the terminating character there as well). So I don't see why this would have worked there?

Another question is whether `show run` shows the self-signed certificate in the same way (as that might be a potential workaround as well).

**Comment by zohassadar** [comment]
>Yeah, the fundamental question to me is why is the hostname# in the certificate name? That really should be avoided at all costs with CLI automation.

There's an unknown history with these devices.  I am not sure if they were configured that way, or if there was some condition that caused the system to use the hostname.  [This blog](https://www.ciscozine.com/how-to-create-self-signed-certificates/) shows what appears to be the system using the hostname for the certificate name in the second example.  That example has a custom trustpoint name though, where the affected devices have what looks like a system generated name (`TP-###..`).  Of course there's always the possibility a user deleted the system generated trustpoint and recreated using the same name.   I tried to recreate on a 3750 using a few options but the device called it `IOS-Self-Sig#<number>.cer` everytime, but it wasn't either of the observed affected versions.  The affected devices are old anyway, so probably not worth any more lab time than what I've already spent.  

> On the face of, I would have expected this to fail on earlier versions of Netmiko (i.e. Netmiko should have been looking for the prompt as the terminating character there as well). So I don't see why this would have worked there?

Using version 3.4.0 and instantiating the session with `fast_cli=False` and using `send_command` with `delay_factor=5` will cause it to [sleep](https://github.com/ktbyers/netmiko/blob/v3.4.0/netmiko/base_connection.py#L1531) for 1 second vs .02 seconds with `fast_cli=True`.  This additional delay would allow the full result to show up before `self.read_channel()` happened.  It wasn't an elegant solution.  


> Another question is whether show run shows the self-signed certificate in the same way (as that might be a potential workaround as well).

The `crypto pki certificate chain` sections don't show up in the running config on some platforms for whatever reason, only the startup config, so no issues with the running config.  In this current use case I am wanting to collect both.

**Comment by ktbyers** [comment]
Okay, that makes sense on Netmiko 3.4.0, but that meant it was basically working because of a bug/deficiency in Netmiko 3.4.0 and earlier.

In other words, Netmiko 3.4.0 and earlier would actually read beyond the terminating pattern if data was available. 

So you made it slow enough so that all the data was available and due to Netmiko's bug/deficiency it grabbed all of this data.

Okay, yeah I don't know why it uses hostname#file.cer. I see this on my IOS-XE device (but it is not a catalyst and is newer than what you are referring to):

```
crypto pki certificate chain TP-self-signed-2174981821
 certificate self-signed 01 nvram:IOS-Self-Sig#2.cer
```

Agreed not worth doing more on this as there is a workaround by explicitly using an expect_string. A bit of a Cisco misdesign/borderline bug though (by putting the hostname# in the actual config).
