### ISSUE TITLE
Netmiko logging has issues with ConnLogOnly

### ISSUE THREAD

**Issue by ktbyers** [ktbyers/netmiko#2826]
Basically multiple calls to it will not reinitialize the logging (including the filename)

Also I am doing a getlogger call where __name__ is netmiko.ssh_dispatcher (which is probably not what I wanted).

**Comment by ktbyers** [comment]
Also ConnLogOnly fails when used with a Context Manager. I should look to fix that.

**Comment by tommy-as** [comment]
Hi @ktbyers,

Does ConnLogOnly suport multiprocessing? 

def main():
    devices = some_function_to_get_devices_and_their_attributes()
    pool = Pool(processes=10)
    data = pool.map(connection, devices)
    
def connection(device):
         device = {
             'ip': device['host'],
             'device_type': device['device_type'],
             'username': device['username'],
             'password': device['password'],
             'global_delay_factor': 4
         }
        net_connect = ConnLogOnly('logfile.txt', **device)
        
        if device['device_type'] == 'huawei':
            command = 'display interface description'
       if device['device_type'] == 'cisco_ios':
           command = 'show interface description'
       if device['device_type'] == 'juniper_junos':
           command = 'show interfaces description'
           
        output = net_connect.send_command(command)

**Comment by ktbyers** [comment]
ConnLogOnly should support multiprocessing just fine. Whether your code is correct or not, you would need to test.

I would pretty strongly recommend you use Python's `Concurrent Futures` instead of trying to use the `multiprocessing` library.

**Comment by laimaretto** [comment]
Hi! This is my first try with `ConnLogOnly()` with netmiko 4.2.0. I'm wiling to store debug info per session, because the classical way of using `logging` mixes all the information in one file, and hence it gets a little problematic to analyze per router info when you have many of them running in parallel.

But even when using `ConnLogOnly()` all of the sessions are also mixed in the same file.

I'm using `from multiprocessing.pool import ThreadPool`  with `apply_async`. Everything works ok, meaning seanding commands and receiving output, but the debug information with `log_file` is being mixed in only one file. Actually, in the file of the first connection ...

I'm doing as follows....

```
def routerLogin(self, connInfo):
   [...]
   debug = self.ip + ".debug"
   conn2rtr = ConnLogOnly(device_type=deviceType, host=ip, port=port, username=tempUser, password=tempPass, fast_cli=False, log_file=debug)

```

anything to double check? thanks!
