### ISSUE TITLE
Improve Netmiko documentation (methods and arguments).

### ISSUE THREAD

**Issue by ktbyers** [ktbyers/netmiko#285]
x

**Comment by ebeahan** [comment]
x

**Comment by ktbyers** [comment]
I think there are one or two other people that might want to help on this task.

**Comment by ktbyers** [comment]
I am definitely out of the loop on auto-documentation so let me know what you think the best way to do this is.

The most pressing thing that is missing is documentation on important Netmiko class and methods and their arguments. It would be nice to have this built from the source code so that the source code docstring just gets updated whenever the method changes.

**Comment by ktbyers** [comment]
Adding @dhanakane

**Comment by ebeahan** [comment]
I've used Sphinx and autodoc with other Python projects, and I've found it's decent to work with. I tossed together a basic example repo and a readthedocs site generated from that repo's docs as a rough example.

https://github.com/ebeahan/autodoc-example

http://autodoc-example.readthedocs.io/en/latest/

**Comment by ktbyers** [comment]
Okay, let me look at it.

**Comment by dhanakane** [comment]
Looks pretty good. How do we get started?

**Comment by ktbyers** [comment]
Sorry am pretty slammed for the next ten days or so. Feel free to run with anything on the autodoc process (that you want to do). 

I will try to follow up after my schedule frees up a bit.

**Comment by ebeahan** [comment]
I haven't had a chance to dig in more myself yet. Will try to suss out some good starting points in the next few days.

**Comment by ktbyers** [comment]
Sounds good. I should have a bit more availability to look at it early next week.

**Comment by ebeahan** [comment]
Here's a few of the minimum steps coming to mind:

- Build out the base framework for sphinx/autodoc for the repo (typically in a ``docs`` or `doc` directory). This includes the initial config of `conf.py` (template selection, path config, etc). Good guide here: http://read-the-docs.readthedocs.io/en/latest/getting_started.html
- Decide how the directory/file structure of the documentation. Since the initial focus is the important Netmiko classes and methods, perhaps keep it simple and build directories for the different device_types and each module as a file?
- Decide what standard to use for formatting the docstrings and which classes/methods to focus on applying that standard on initially. Conquer and divide among anyone wanting to help in the effort.
- Once the docs are added in the repo, @ktbyers can use a service like readthedocs.io to pull them in from the repo and build them out.

Some of the initial sphinx config might be best set by @ktbyers, or I can work on a PR with some of the initial doc framework. Once the framework and direction are set carving up the task of updating the docstrings should be straight-forward.

**Comment by dhanakane** [comment]
Happy to follow your lead Eric!

**Comment by ktbyers** [comment]
@ebeahan @dhanakane Can we do a test of the workflow with the ConnectHandler arguments i.e. try to set this up with this one class and I think that will give me a better sense of the overall workflow.

Here are the ConnectHandler arguments:

```
    def __init__(self, ip='', host='', username='', password='', secret='', port=None,
                 device_type='', verbose=False, global_delay_factor=1, use_keys=False,
                 key_file=None, ssh_strict=False, system_host_keys=False, alt_host_keys=False,
                 alt_key_file='', ssh_config_file=None, timeout=8):
```

It definitely would help me if you could submit an issue PR on it, but if not I can try to do it.

**Comment by ebeahan** [comment]
Submitted https://github.com/ktbyers/netmiko/pull/296 as a test. To preview the docs:
 
```
cd docs
pip install -r docs-requirements.txt
make html
cd build/html
python -m SimpleHTTPServer
```

Let me know what you think.

**Comment by ktbyers** [comment]
@ebeahan @dhanakane FYI, I started testing (very briefly trying to get this to work with readthedocs.io).
