### ISSUE TITLE
Boolean return values versus string return values

### ISSUE THREAD

**Issue by ktbyers** [ktbyers/netmiko#29]
I am currently returning strings instead of booleans for some functions like enable(), config_mode() would returning booleans be more logical?

**Comment by ravenblue12** [comment]
Under normal circumstances you want to get an boolean return value when you enter an new state. I only want to get the output for debugging.

**Comment by ktbyers** [comment]
For methods like enable() and config_mode() IMO it is better to have it either work (which is validated as part of the method) or raise an exception.  In other words, if you say .enable() and it doesn't actually go into enable your program should crash (unless you explicitly handle the exception).

For these methods (enable(), config_mode()) what added value is there to returning a boolean since you already know it worked?

Passing the output back was helpful for debugging and for returning CLI session information (as you have a chain of output as it went through multiple methods).  

Although it does add some complexity too the code...

**Comment by ravenblue12** [comment]
To raise an exception is no bad idea, because it is very important to ensure that you are in that mode!

**Comment by ktbyers** [comment]
Yes, I agree.  I think it should crash (i.e. exception) unless the user
explicitly handles the exception.



Kirk

On Sat, Jan 31, 2015 at 1:20 AM, Rene Plattner <notifications@github.com>
wrote:

> To raise an exception is no bad idea, because it is very important to
> ensure that you are in that mode!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ktbyers/netmiko/issues/29#issuecomment-72310717>.
>



-- 
Kirk Byers
CCIE #6243 emeritus
ktbyers@twb-tech.com
*http://pynet.twb-tech.com <http://pynet.twb-tech.com/blog>*
(415) 264-6270
Simplify your network management through automation

**Comment by supertylerc** [comment]
Debugging info should be in the exception, not returned as part of the method's return value.  My vote is for returning a boolean value and raising an exception with debugging info on error.

**Comment by yourteamneedsadam** [comment]
@ktbyers I think your plan is the Pythonic way - raise an exception if anything goes wrong and otherwise don't use the `return` statement. That'll result in Python's default return of `None`, which means the function wasn't intended to return a value. That works well with the name. When I read something like `enable()` I wouldn't expect to get output. Whereas if it were called `is_enabled()` I would.

Where to put debug info is a little tricker. For data read off the paramiko channel (shell output), I think the best way is to append it to an attribute on the object (connection state goes in the connection object) and print it out with Python's `logging` library whenever it's in `DEBUG` and before raising an exception. Not 100% sure I'm following on that point though. @ktbyers I poked around some of the methods you mentioned and I think I get the idea, but is there a specific one I could look more closely at?

**Comment by ktbyers** [comment]
@yourteamneedsadam Yes, I think this probably could be improved. I am currently returning data that probably should be sent to a logging channel.

Let me see if I can document what I do on various methods. We can then discuss if it makes sense to update some of them.

I will try to post a quick summary in this issue thread.

**Comment by ktbyers** [comment]
I am going to leave it as is. I don't think it is worth changing at this point.
