### ISSUE TITLE
How to compare two lists in python

### ISSUE THREAD

**Issue by unustayyab123** [ktbyers/netmiko#3137]
Hi guys

I am having issue with comparing two python lists, it is not giving expected result. pls check below script

tcp_ports = ["TCP-445","TCP-500","TCP-540","TCP-544","TCP-567"]
serviceport_tcp_list= ["445","446","500"]

for item in serviceport_tcp_list:
    if item in tcp_ports:
        matching = [s for s in tcp_ports if item in s]
        print(matching)
    else:
       print("not in list")
  
i am comparing item in two lists, if match found then return the match value  ,if not return "not in list", but this is not working , iam getting only "not in list"

any suggestions?

**Comment by SincerelyAdel** [comment]
Hello👋 

So first off you got 2 lists with strings in them, the second list has a string (text) containing a number that is also found in the first list. However, since both data types are strings, when you compare them they need to be IDENTICAL (Ex. if "ABC" == "ABC" yields true), in here you only compare the number with "TCP-{number here}", obviously both are not identical so this always yields false.

One way to do this would be to use the in operator:

For i in service_ports:
Matchings = [match for match in tcp_ports if match in i]
Print(matchings)
If len(matchings) == 0:
Print("no matchings")


This should run through all service ports and check if any are found in tcp ports and then prints them, if it did all these steps and no ports are matching, then it will declare that there are no matchings.

Side note: you don't need the first if since you have one in the Generator object (the line that defines matchings).

**Comment by ktbyers** [comment]
This is not a Netmiko issue i.e. this is more appropriate for Stack Overflow or some other forum.
