### ISSUE TITLE
IOError: Search pattern never detected in send_command()

### ISSUE THREAD

**Issue by rajatguptarg** [ktbyers/netmiko#337]
Hi,

I am using netmiko and python to connect to Huawei device which runs some command and get the output from the device.

python version = 2.7.10

Code sample:

`output = self.net_connect.send_command('display board 0')`

where `net_connect` is netmiko object.

Error:

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_lZam52/ansible_module_huawei_command.py", line 270, in <module>
    main()
  File "/tmp/ansible_lZam52/ansible_module_huawei_command.py", line 259, in main
    is_changed, is_error, result = execute(parameters)
  File "/tmp/ansible_lZam52/ansible_module_huawei_command.py", line 219, in execute
    manager.enable_config()
  File "/tmp/ansible_lZam52/ansible_module_huawei_command.py", line 106, in enable_config
    self.net_connect.send_command(CONFIG, delay_factor=DELAY_FACTOR)
  File "/usr/local/lib/python2.7/dist-packages/netmiko/base_connection.py", line 673, in send_command
    search_pattern))
IOError: Search pattern never detected in send_command_expect: rsa59\-1\-dsl\#
```

**Comment by ktbyers** [comment]
Can you post your enable_config() method?

**Comment by rajatguptarg** [comment]
The enable config method is:

```
def enable_config(self):
    self.net_connect.send_command('enable', delay_factor=2)
    self.net_connect.send_command('config', delay_factor=2)

```

**Comment by ktbyers** [comment]
@rajatguptarg Yes, you probably don't want to do that in that way.

Use the Netmiko .enable() and send_config_set() methods instead.

send_config_set() should automatically handle entering and exiting of config mode. It takes a list of config commands.

Your earlier error is probably caused due to the fact that doing what you did above changes the prompt which then can cause problems with the send_command() method (as it is looking for the trailing prompt).
