### ISSUE TITLE
Please consider changing hardcoded poetry version

### ISSUE THREAD

**Issue by dtantsur** [ktbyers/netmiko#3415]
### Description of Issue/Question

Currently, netmiko [hardcodes a specific poetry version](https://github.com/ktbyers/netmiko/blob/1c75ca31a13e2ab1844078a8e1b1fd5f77c51097/pyproject.toml#L2). This makes my life as a Fedora packager somewhat harder since I need to patch it out (Fedora has a much newer poetry). Would it be possible to specify a minimum required version instead?

**Comment by ktbyers** [comment]
This is really only for Netmiko `development` work, can you explain why it matters (from your perspective)?

The problem on my side is its pretty annoying for the CI-CD system to break because of tooling. So I have pretty strong incentives to pin the version of these development tools.

Do you have a version that works for you?

**Comment by dtantsur** [comment]
Sorry, somehow missed the notification. This request has been implemented as part of https://github.com/ktbyers/netmiko/pull/3444, but just to close the loop on it: as any other package, Poetry is a moving target in Linux distributions. I cannot tell you which version we have because tomorrow a bugfix release comes, and we have a different version, and netmiko no longer builds.
