### ISSUE TITLE
code-review - why normalize_linefeeds in cisco_xr_ssh.py

### ISSUE THREAD

**Issue by nkaliape** [ktbyers/netmiko#350]
Why do we need static method when we have 'normalize_linefeeds' already in base definition?

telnet xr connection does NOT get the commit implementations of XR.
Ideally OO looks like Base -> CiscoBase -> CiscoSSHConnection -> XR_SSH
                                                                  -> CiscoTelnetConnection -> does NOT have commit/other methods (lost in cisco_xr_ssh) 

Does it need refactoring? Base -> CiscoBase -> CiscoBaseXR -> CiscoXrSSH / CiscoXrTelnet ?

**Comment by ktbyers** [comment]
@nkaliape The staticmethod question is independent of whether we need normalize_linefeeds in cisco_xr_ssh.py or not. 

normalize_linefeeds is needed because it is different than the normalize_linefeeds in base.

Currently, there is no telnet implementation for Cisco XR.

Yes, if someone wants to build a telnet implementation we should probably have something like the following (I need to do a similar restructuring for Cisco IOS).

BaseConnection > CiscoBaseConnection > CiscoXr > CiscoXrSSH
