### ISSUE TITLE
hi guys, can i grab router/switch temperature, cpu utilization, and memory usage and convert it to graph using python??

### ISSUE THREAD

**Issue by NedySuprianto** [ktbyers/netmiko#455]
hi guys,i have router/switch temperature, cpu utilization, and memory usage (got it from CLI) and can i convert it into graph with python?

**Comment by ktbyers** [comment]
Yes, here is similar example that does some proof-of-concept graphing of interface data.

There are much better open-source solutions for graphing time series data, however.

**Comment by maximumG** [comment]
We did such thing in my previous job by using:

 - Netmiko to interact with the device and send some commands to gather the output (CPU, temperature, CAM table,...)
- isolate and grab some relevant information from the output using TextFSM library
- insert these data into database

**Comment by NedySuprianto** [comment]
@ktbyers yes, i think so for a better solution is open-source, but i just want to try build simple code to generate output cli to graph.

@maximumG now i do a same project like you did previously, need lots of examples for me as a newbie programer :), thanks for your information

**Comment by maximumG** [comment]
@NedySuprianto : basically we build a library that can be used as a translator between cli output gather and a JSON data-structure. The idea is to ask something to our library (e.g : cam table, interface statstics) and it renders a python/JSON datastructure as output. This output can then be used however you want (insert in database, graph,..). We also adapt this library to ansible as an ansible module so that multi-processing is available out of the box.

As soon as I have some time, i will release it under GPL licence on github 😄 and obviously keep you updated.
