### ISSUE TITLE
IOError: Search pattern never detected in send_command_expect:

### ISSUE THREAD

**Issue by prince07** [ktbyers/netmiko#461]
Dear, 

I try to send some command through net_connect.send_command("command") but is showing error. 

> IOError: Search pattern never detected in send_command_expect:

my code. 

`net_connect = ConnectHandler(**cisco_4500)

net_connect.enable()
print net_connect.find_prompt()
net_connect.config_mode()
print net_connect.find_prompt()

config_cmd = [

'int range vlan 20-25, vlan 40, vlan 50-51, vlan 60, vlan 110' ,
'no ip helper-address 10.254.111.123' ,
'ip helper-address 10.252.165.80' ,
'ip helper-address 10.254.111.123',
'int range vlan 30-35, vlan 52-53, vlan 70, vlan 80-81, vlan 90',
'no ip helper-address 10.254.111.213' ,
'ip helper-address 10.252.165.83',
'ip helper-address 10.254.111.213'

]

for cmd in config_cmd:
    print cmd
    output = net_connect.send_command(cmd)
    print output
net_connect.disconnect()`

error. 

> File "D:/ADEC_py_Work/ping-test/4500_iphelper_config.py", line 37, in <module>
    output = net_connect.send_command(cmd)
  File "C:\Python27\lib\site-packages\netmiko-1.4.0-py2.7.egg\netmiko\base_connection.py", line 802, in send_command
    search_pattern))
IOError: Search pattern never detected in send_command_expect: s256\\-m01\\-csw001\\(config\)\\#

Process finished with exit code 1

my host name is s256-m01-csw001 . why is searching s256\\-m01\\-csw001\\

**Comment by ktbyers** [comment]
@prince07 For config commands you need to use the send_config_set() method.

See near the bottom of this page:

https://github.com/ktbyers/netmiko

So:

```
net_connect = ConnectHandler(**cisco_4500)
net_connect.enable()
print net_connect.find_prompt()

config_cmd = [
  'int range vlan 20-25, vlan 40, vlan 50-51, vlan 60, vlan 110' ,
  'no ip helper-address 10.254.111.123' ,
  'ip helper-address 10.252.165.80' ,
  'ip helper-address 10.254.111.123',
  'int range vlan 30-35, vlan 52-53, vlan 70, vlan 80-81, vlan 90',
  'no ip helper-address 10.254.111.213' ,
  'ip helper-address 10.252.165.83',
  'ip helper-address 10.254.111.213'
]

output = net_connect.send_config_set(config_cmd)
net_connect.disconnect()`
```

Note, your helper-address configs aren't associated with an interface? 

Also, note, you might want to just enumerate the VLANs and not use interface range. I say this because interface range can be slow and it is just a shortcut for the individual commands. Instead of doing this, you can just do it programmatically and configure each one.

```
vlans_to_config = [
    30,
    31,
    32,
    33,
    34,
    35
     # the rest of them
]

vlan_commands = []
for vlan_number in vlans_to_config:
    cmd = 'interface vlan {}'.format(vlan_number)
```

Something like this then add these vlan_commands to your list of commands (at the right location).
