### ISSUE TITLE
Fix HP ProCurve enable method to use a while loop

### ISSUE THREAD

**Issue by ktbyers** [ktbyers/netmiko#577]

**Comment by gininfra** [comment]
I copy and paste the netmiko/hp/hp_procurve_ssh.py to netmiko/hp/hp_procurvejinhua_ssh.py for HP Procurve 1920/1910 which its "_cmdline-mode on"'s password is "Jinhua1920unauthorized:, and this is the modification: https://pastebin.com/ftjk5rVb

And another copy for the HP Procurve 1920/1910 which use "512900" as its "_cmdline-mode on"'s password: https://pastebin.com/ffY69pkT

And little modification in netmiko/hp/__init__.py: https://pastebin.com/gSTSUWqi
And little modification in netmiko/ssh_dispatcher.py: https://pastebin.com/HXH8QW64

**Comment by ginsigitgin** [comment]
in HP Procurve 1910, I have to go to enable by writing the send_command_timing like this:
conn = ConnectHandler(**device)
conn.send_command_timing("_cmdline-mode on \n Y\nJinhua1920unauthorized\nscreen-length disable \n display mac-address")

in HP Procurve 1920, I have to go to enable by writing the send_command_timing like this:
conn = ConnectHandler(**device)
conn.send_command_timing("_cmdline-mode on \n Y\n512900\nscreen-length disable \n display mac-address")

As far as I know, both enable passwords ("Jinhua1920unauthorized" and "512900") are from factory default settings and cannot be changed.

Can you add this modification to netmiko?

Big thanks!

**Comment by ginsigitgin** [comment]
I copy and paste the `netmiko/hp/hp_procurve_ssh.py` to `netmiko/hp/hp_procurvejinhua_ssh.py` for HP Procurve 1920/1910 which its `_cmdline-mode on`'s password is `Jinhua1920unauthorized` and this is the modification: https://pastebin.com/ftjk5rVb

And another copy for the HP Procurve 1920/1910 which use `512900` as its `_cmdline-mode on`'s password: https://pastebin.com/ffY69pkT

And little modification in `netmiko/hp/__init__.py`: https://pastebin.com/gSTSUWqi
And little modification in `netmiko/ssh_dispatcher.py`: https://pastebin.com/HXH8QW64

Sorry for what can I do only copy, paste and edit (I haven't write code for a long, long, too long)

**Comment by trussmky** [comment]
My HP 1910 switches respond better with the HP_Comware settings.  they are running V5.20  build 1519P03.

I did not have luck with your methods, So duplicated the hp_comware.py, renaming it hp_comware512900.py  
I added 5 lines into the HPComwareBase class at line 21 which forces the switch into command line mode.

`        #log into command line mode
        time.sleep(0.3 * delay_factor)
        self.write_channel("_cmdline-mode on \n")
        self.write_channel("y \n")
        self.write_channel("512900\n")
`
I also added a call to set_base_prompt() in config_mode() because the program was timing out with the new prompt style

in netmiko/hp/__init__.py I added one line and replaced __all__ with the following
`from netmiko.hp.hp_comware512900 import HPComware512900SSH, HPComware512900Telnet

__all__ = ['HPProcurveSSH', 'HPProcurreTelnet', 'HPComwareSSH', 'HPComwareTelnet', 'HPComware512900SSH', 'HPComware512900telnet', 'HPProcurveJinhuaSSH', 'HPProcurve512900SSH']
`
A also added updated netmiko/ssh_dispatcher.py with the following lines:

Line 50 - update
`from netmiko.hp import HPProcurveSSH, HPProcurve512900SSH, HPProcurveJinhuaSSH, HPComwareSSH, HPProcurveTelnet, HPComwareTelnet, HPComware512900SSH, HPComware512900Telnet,

`
Line 128 - within CLASS_MAPPER_BASE add
`    "hp_comware512900": HPComware512900SSH, # added for 1910`

Line 197 - #add telnet drivers
`CLASS_MAPPER["hp_comware512900_telnet"] = HPComware512900Telnet # add for 1910`

Sorry if this is messy, I am a git and Python noob

**Comment by ktbyers** [comment]
Fixed here:

https://github.com/ktbyers/netmiko/pull/1481

**Comment by ktbyers** [comment]
@ginsigitgin That looks like probably a separate issue--you probably should open it as a new issue if it is still relevant to you.

**Comment by Malchambar** [comment]
Old thread... I just across the same issue.

I came across some 1920s today with their funky easter egg script to get into "enabled" CLI. How do I structure my scripts (I have a collection of them doing different tasks) to incorporate this update (or logic, whatever it is).

I clearly can't just use hp_comware for my device type and the Netmiko figures the rest out.

Is there some sort of option I can pass to netmiko in the list of variables... Like "Warning Larks Vomit Ahead ^H^H^H I mean an HP1920 switch incoming?

I just looked through the hp_comware.py and hp_procurve.py files and I don't see any related logic... Any help would be appreciated.

Martin
