### ISSUE TITLE
Investigate using system-wide SSH config file

### ISSUE THREAD

**Issue by ktbyers** [ktbyers/netmiko#597]
...as a default, what are the implications of this.

**Comment by tonypnode** [comment]
just throwing it out there, in an auditing app I'm developing that uses Netmiko, I do just that. I created a class called ConnectionProfiles and define a default_conn_profile classmethod that imports a yaml file with the data i need for all of my devices. 

I will add that for security sake, I am going to modify it so that the system that does these audits uses a rsa key instead.
