### ISSUE TITLE
Incomplete import of textfsm

### ISSUE THREAD

**Issue by dtantsur** [ktbyers/netmiko#672]
I'm trying to package Netmiko 2.0.1 for Fedora, and run into the following issue when importing the package in buildroot:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "netmiko/__init__.py", line 8, in <module>
    from netmiko.ssh_dispatcher import ConnectHandler
  File "netmiko/ssh_dispatcher.py", line 4, in <module>
    from netmiko.a10 import A10SSH
  File "netmiko/a10/__init__.py", line 2, in <module>
    from netmiko.a10.a10_ssh import A10SSH
  File "netmiko/a10/a10_ssh.py", line 4, in <module>
    from netmiko.cisco_base_connection import CiscoSSHConnection
  File "netmiko/cisco_base_connection.py", line 3, in <module>
    from netmiko.base_connection import BaseConnection
  File "netmiko/base_connection.py", line 24, in <module>
    from netmiko.utilities import write_bytes, check_serial_port, get_structured_data
  File "netmiko/utilities.py", line 9, in <module>
    from netmiko._textfsm import _clitable as clitable
  File "netmiko/_textfsm/__init__.py", line 3, in <module>
    from netmiko._textfsm import _clitable
  File "netmiko/_textfsm/_clitable.py", line 34, in <module>
    import copyable_regex_object
```

Apparently, the imported code still imports "textfsm" and "copyable_regex_object". So it seems that it's still required to install textfsm, which, as far as I get gather, is problematic on Windows (and is not packaged for Fedora).

**Comment by ktbyers** [comment]
@dtantsur How did you do the netmiko installation?

Yes, you still need to install textfsm. TextFSM installs fine on Windows; it fails on import due to other dependencies.

```
$ cat requirements.txt 
paramiko>=2.0.0
scp>=0.10.0
pyyaml
pyserial
textfsm
```

**Comment by dtantsur** [comment]
@ktbyers I'm the Fedora packager for netmiko :) So, I need everything to be packaged and 'pip install' is certainly not an option. What was the reason to intern textfsm only partly? For me it seems logical to intern the complete library (plus your fixes), but I don't have enough context.

If that's the way it should be, we will have to package textfsm for Fedora (will delay packaging 2.0.x since I don't have time for it) and un-intern it from your package via a downstream patch. It's not too much work, but I'm trying to understand your intentions before making any decisions on my side :)

**Comment by ktbyers** [comment]
@dtantsur Nice to meet you Dmitry. Thanks for explaining your context.

Here are the issues with TextFSM. There are three versions of it (gtextfsm, jtextfsm, and textfsm). I believe gtextfsm is dead and no longer maintained; jtextfsm doesn't have the clitable component which I need.

So that only leaves `textfsm` which is maintained by Google. Unfortunately, they used dependencies that were Linux only dependencies. Even though in the Netmiko use case, I don't need any of these Linux-TextFSM specific things.

The consequence of this was that loading textfsm breaks Netmiko on Windows (i.e. it would cause just an import of netmiko to break on Windows).

This really only happens in the `clitable` part of TextFSM and not in the `textfsm` part. Consequently, I wanted to be able to get updates and bugfixes for textfsm without having to maintain my own version of it.

The `clitable` part is a pretty simple function and I doubt other changes to `textfsm` will break it. 

So that is why I put only this `clitable` part internal to Netmiko. 

I am open to other solutions though.

From a practical standpoint, you can stay on Netmiko 2.0.0. That 2.0.1 fix was almost entirely to fix that Windows issue.

This will give us more time to resolve the issue (i.e. we can figure out a solution that works for the next Netmiko release).

**Comment by dtantsur** [comment]
@ktbyers I see, thanks for the nice explanation! Unfortunately, 2.0.0 is also not an option until textfsm is packaged (I can try looking into it, of course, but again - ENEVERENOUGHTIME :). Meanwhile, do you think it's reasonable to import textfsm modules on demand? If I remember the patch correctly, they are only used in one function and with an explicit flag to enable, right? This may allow me to move to 2.0.0 without blocking on packaging textfsm. What do you think?

**Comment by ktbyers** [comment]
Yes TextFSM is only used in two methods (`send_command()` and `send_command_timing()`) and defaults to disabled.

So we could set flag like TEXTFSM_INSTALLED and then add some additional logic that checks this flag before using TextFSM. 

That is probably reasonable in the short-run; in the long-run it would be nice to have that feature.

Another option is I could just bring the whole TextFSM package into Netmiko. It doesn't change that much (i.e. there aren't many commits being made to it...two since May of 2017).

**Comment by dtantsur** [comment]
@ktbyers both options look good to me, so it's up to you what you think fits the project better.

**Comment by ktbyers** [comment]
We probably need to revisit since textfsm by google changed into a True-package so I need to research the implications of that for Netmiko.

I never did either of the above solutions either.

**Comment by ktbyers** [comment]
Not sure if we need to do more work here @dtantsur from your perspective?

**Comment by dtantsur** [comment]
It would be cool to un-vendor the package, but we have worked around it by packaging textfsm in Fedora/RDO.

**Comment by ktbyers** [comment]
Unfortunately, I think we can't un-vendor it as Google's TextFSM breaks TextFSM on Windows (for things that are irrelevant to Netmiko's use of it).


Thanks for the update.

**Comment by ktbyers** [comment]
I am going to close this as I don't think there are any remaining actions here.
