### ISSUE TITLE
Encrypted password in Netmiko

### ISSUE THREAD

**Issue by fixlensmith** [ktbyers/netmiko#771]
I need to run my script automatically by cron. so i need to input my password in the script. i need to encrypt using SHA256 (pkdbf2-sha256), using passlib module.
how netmiko can authentica using  encryption password?

**Comment by ktbyers** [comment]
Assuming you are using username/password authentication on the device, then you would need to provide the cleartext password to the device (i.e. your program would have to decrypt the password and provide the clear password).

One possible solution for this problem is probably to use SSH keys for authentication.
