### ISSUE TITLE
Add tests that use SSH keys

### ISSUE THREAD

**Issue by ktbyers** [ktbyers/netmiko#81]

**Comment by ghmj2417** [comment]
Does this include the use of being able to use pkey?  I need to present a private key to my network device, rather than a password.  I can't find a way to do it with this implementation.

**Comment by ktbyers** [comment]
@ghmj2417 No the above is referring to standard public key / private key authentication.

**Comment by ghmj2417** [comment]
Thank you for the response.  I apologize ahead of time if this is not the right place to bring up my concern.  I'm in a situation where I have to use private key(s) to authenticate to network devices.  I believe I have discovered what is wrong and the path to fix it.  The path might need to be altered a bit because I am not a developer.  I need to be able to specify key_file/key_filename but the problem is scp_handler.py doesn't check to see if there is a key file.  Based off of the scp_handler.py code, in class SCPConn, def estabsligh_scp_conn, self.scp_conn.connect needs to have an arg for key_filename=self.ssh_ctl_chan.key_file.  However, with this setup, base_connection.py needs to expose the key_file.  I just added self.key_file = key_file to class BaseSSHConnection, def __init__.  I have no idea if this is how it would need to be fixed to support private keys but making those changes allowed this to work.
Also, great module by the way.  It's going to make automatic deployments much easier. 

    On Friday, April 29, 2016 12:33 PM, Kirk Byers <notifications@github.com> wrote:
 

 @ghmj2417 No the above is referring to standard public key / private key authentication.—

**Comment by ktbyers** [comment]
@ghmj2417 So you are trying to SCP files to network device and use SSH keys?

**Comment by ghmj2417** [comment]
Yes. Instead of using a password, my private key is used to authenticate the SSH session.

**Comment by ktbyers** [comment]
Yes, but you are looking to do secure copy not just SSH interacting with CLI?

**Comment by ghmj2417** [comment]
Yes, that is correct.

**Comment by ktbyers** [comment]
Yes, your suggestion above sounds like the right direction to implement this. I might look at this in a ~week; I won't get to it before then.

**Comment by ghmj2417** [comment]
Sounds good. Thank you for taking care of this.

**Comment by ghmj2417** [comment]
Were you able to check into this?

**Comment by ktbyers** [comment]
No, I haven't made time to look at this. I probably won't get to it for a while. I doubt I will look at this before August.

Feel free to submit a pull request on it, however.

**Comment by ktbyers** [comment]
Tests on Linux for this have been implemented. Still need to add tests at least for Cisco IOS.
