### ISSUE TITLE
Support Python3

### ISSUE THREAD

**Issue by ktbyers** [ktbyers/netmiko#84]
Placeholder to figure out the issues involved in doing htis.

**Comment by plucena24** [comment]
The following  components are the main changes needed for the netmiko library to be compatible with Python 2 and Python 3. 

- Using the print() function instead of the print statement
```
if debug:
  print("In set_base_prompt")
```
- Changing relative import statements to absolute
```
from netmiko.cisco.cisco_ios_ssh import CiscoIosSSH
```
or
```
from . cisco_ios_ssh import CiscoIosSSH
```
instead of 

```
from  cisco_ios_ssh import CiscoIosSSH
```

- Using the unicode 'sandwich' pattern where input bytes (output from SSH sessions, files read from disk, etc) are decoded to unicode as soon as possible. Unicode strings are carried throughout the program, and if need to output, encoded back to bytes right before output. 
  - All string manipulation code will not be affected as long as all input bytes are decoded to unicode right away.
  - utf-8 encoding should be used
``` 
output = self.remote_conn.recv(MAX_BUFFER).decode('utf-8')
```
- For opening files, the  `io` module's `open()` method should be used, as it has an `encoding` argument just like the builtin `open` function in Python 3. This will take care of any input bytes read from disk entering the program.

```
import io
with io.open(config_file, encoding='utf-8') as cfg_file:
    return self.send_config_set(cfg_file, **kwargs)
```

- ANSI ESC sequences currently using `chr(27)` will continue working under Python3 without modification, as ASCII values map directly to the same values in Unicode code points.

These are the main factors that would need to change in order to be compatible with Python3.

**Comment by daenney** [comment]
* `io.open` and the `as exc_var` syntax are not supported in Python versions older than 2.6
* `print()` requires a `from __future__ import print_function`
* The `.decode('utf-8')` stuff can probably be omitted if you go with `from __future__ import unicode_literals` but would have to test that

**Comment by ktbyers** [comment]
@daenney I missed this comment earlier. Let me know if you are interested in working on this Python3 support for netmiko. There is a good chance Pablo and I are going to work on it. I want to look at it some this weekend.

For Python2, we are only going to support Python2.6 and Python2.7.

**Comment by daenney** [comment]
I've done some porting of codebases to be Python2.6+ compatible so I can certainly help out but I don't have access to any of the hardware to actually test this stuff. Especially the unicode handling makes me a bit nervous.

**Comment by ktbyers** [comment]
@plucena24 I think all of the imports use absolute paths now.

**Comment by ktbyers** [comment]
@daenney Yes, I should have the ability to test on Cisco IOS, Cisco IOS XE, ASA, HP ProCurve, and Juniper. I think @plucena24 has the ability to test on NX-OS, and IOS-XR as well as some of the same platforms that I have.

I am thinking about setting up Travis-CI so that we could test on PY2.6, 2.7, 3.3 and 3.4 and automate some of the testing.

**Comment by ktbyers** [comment]
I assume that we would do a single integrated code that would support PY2.6, 2.7, 3.3, and 3.4?

**Comment by plucena24** [comment]
@ktbyers yes, that would be the preferred route in my opinion - having a single package that works on both.

**Comment by ktbyers** [comment]
Created python3_port branch

**Comment by ktbyers** [comment]
I have ran unit tests on this using Python 3.4.3 and Python 2.6.9 using Cisco IOS, Juniper, HP ProCurve, and Arista. And Cisco ASA on Python 2.6.9 (still need to test ASA on Python 3.4.3).

These all pass.

It would be good test Cisco NX-OS, IOS-XR, and IOS-XE. I can probably test IOS-XE.

**Comment by ktbyers** [comment]
@plucena24 Let me know if you can test on NX-OS, and IOS-XR? I can help getting the tests running if TESTING.md is not clear.

**Comment by plucena24** [comment]
I am working on that at the moment...was having issues installing paramilo
for py3.4 on windows, got it sorted out now.

**Comment by daenney** [comment]
I've had a look at the python_3 branch, so far so good as far as I can tell. Do network vendors still not provide some kind of virtual lab facility that would allow to (automate) test against a variety of their hardware?

**Comment by ktbyers** [comment]
@daenney There are various things available for testing. It seems like virtual devices in your own test environment is probably the easiest way to go, however.

**Comment by ktbyers** [comment]
@plucena24 FYI, I have merged this python3_port code back into the master branch.

**Comment by daenney** [comment]
Time to close the issue then :)

**Comment by ktbyers** [comment]
Yep...
